      SUBROUTINE CACALC(B,WING)
C
C***  COMPUTES WING CN,CA
C
      DIMENSION B(1),WING(1)
      COMMON/CONSNT/ PI,DR,UNUSED,RAD
      COMMON/OVERLY/ NLOG,NMACH,I,NALPHA
      DO 1000 M=1,NALPHA
C
C*********     REVISED EQUATION FOR (CN)WING AND (CA)WING
C              COMPUTE SIN(ALPHA) AND COS(ALPHA)
C
         CA=COS(B(M+22)/RAD)
         SA= SIN(B(M+22)/RAD)
C
C***     COMPUTE REVISED (CN)WING AND STORE IN WING(M+60)
C
         WING(M+60)= WING(M+20)*CA + WING(M)*SA
C
C***     COMPUTE (CA) WING AND STORE IN WING(M+80)
C
         WING(M+80)= WING(M)*CA - WING(M+20)*SA
 1000 CONTINUE
      RETURN
      END
