      SUBROUTINE CDWBT
C
C**** TRANSONIC WING-BODY-TAIL CD - DATCOM SECTION 4.5.3.2
C
      COMMON /IBODY/  PBOD, CDB(20)
      COMMON /IHT/    PHT,  CDH(20),CLH(20)
      COMMON /IVT/    PVT,  CDOV
      COMMON /IBW/    PBW,  CDWB(20)
      COMMON /IBV/    PBV,  CDBV(20)
      COMMON /IBWH/   PBWH, CDBWH(20)
      COMMON /IBWV/   PBWV, CDBWV(20)
      COMMON /IBWHV/  PBWT, WBTCD(20)
      COMMON /IDWASH/ PDWA, QOQI(20),EPS(20)
      COMMON /SBETA/  STB(135),TRA(108),TRAH(108)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /OVERLY/ NLOG,NMACH,NZ,NALPHA
C
      EQUIVALENCE (TRA(73),CDOWB), (TRAH(108),CDOH), (TRA(75),CDOWBT)
      LOGICAL FLAG
C
      CDOWBT = WBTCD(1)
      IF(CDOV.EQ.UNUSED.AND.CDOWBT.EQ.UNUSED) GO TO 1010
      IF(CDOV.EQ.UNUSED)CDOV=CDOWBT-CDOWB-CDOH
      DO 1000 I=1,NALPHA
      FLAG = ABS(CDWB(I)) .EQ. UNUSED .OR. ABS(CDH(I)) .EQ. UNUSED
     1  .OR. ABS(QOQI(I)) .EQ. UNUSED .OR. ABS(CLH(I)) .EQ. UNUSED
     2  .OR. ABS( EPS(I)) .EQ. UNUSED
      IF(FLAG) GO TO 1000
      WBTCD(I)=CDOV+CDWB(I)+QOQI(I)*(CDH(I)*COS(EPS(I))+CLH(I)*
     1         SIN(EPS(I)))
 1000 CONTINUE
 1010 CONTINUE
      DO 1020 I=1,NALPHA
         FLAG = CDOV .NE. UNUSED .AND. ABS(CDB(I)) .NE. UNUSED
         IF(FLAG) CDBV(I)=CDB(I)+CDOV
         FLAG = CDOV .NE. UNUSED .AND. ABS(WBTCD(I)) .NE. UNUSED
         IF(FLAG) CDBWH(I)=WBTCD(I)-CDOV
         FLAG = CDOV .NE. UNUSED .AND. ABS(CDWB(I)) .NE. UNUSED
         IF(FLAG) CDBWV(I)=CDWB(I)+CDOV
 1020 CONTINUE
      RETURN
      END
