      SUBROUTINE CLMCH0(A,B,CLALPA,CLMAX,CLMAXL,CLAMO,WING,ITTY)
C
C***  COMPUTES LIFTING SURFACE CL AT MACH=0
C
      COMMON /OVERLY/ NLOG,NMACH,M,NALPHA,IG
      COMMON /FLGTCD/ FLC(93)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1      HEAD,PRPOWR,JEQPOW,LOASRT,TVTPAN,SUPERS,SUBSON,TRANSN,HYPERS
      LOGICAL       FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1      HEAD,PRPOWR,JEQPOW,LOASRT,TVTPAN,SUPERS,SUBSON,TRANSN,HYPERS
      DIMENSION A(1),B(1),CLALPA(1),CLMAX(1),WING(1)
C
C     ----COMPUTE CLW S FOR MACH=0.
C
      B(1)=0.
      A(131)=CLALPA(1)
      IF(TRANSN)A(131)=CLAMO
      A(132)=CLMAXL
      B(2)=1.0
      WSAVE=CLMAX(1)
      CLMAX(1)=CLMAXL
      DO 1000 K=1,20
         WING(K)=0.0
 1000 CONTINUE
      M=1
      IF(ITTY .EQ. 0) CALL M15O17
      IF(ITTY .NE. 0) CALL M16O20
C
C     ----STORE ALL CLWS FOR MACH=0.
C
      B(48)=WING(101)
      NALPHA=FLC(2)+.5
      DO 1010 J=1,NALPHA
         B(J+2)=WING(J+20)
 1010 CONTINUE
      A(127)=B(43)
      A(126)=B(49)
      CLMAX(1)=WSAVE
      RETURN
      END
