      SUBROUTINE CLWBT
C
C***  COMPUTES TRANSONIC WING BODY TAIL CL
C
      COMMON /IBODY/  PBOD, CDB(20),CLB(20)
      COMMON /IHT/    PHT,  CDH(20),CLH(20),HT(60),CLAH
      COMMON /IBW/    PBW,  CDBW(20),CLBW(20),BW(60),CLABW
      COMMON /IBV/    PBV,  CDBV(20),CLBV(20),BV(60),CLABV
      COMMON /IBWH/   PBWH, CDBWH(20),CLBWH(20),BWH(60),CLABWH(20)
      COMMON /IBWV/   PBWV, CDBWV(20),CLBWV(20)
      COMMON /IBWHV/  PBWT, CDBWT(20),CLBWT(20),BWT(60),CLABWT(20)
      COMMON /IDWASH/ PDWA, QOQI(20),EPS(20),DEODA(20)
      COMMON /FLGTCD/ FLC(95)
      COMMON /SYNTSS/ XCG,XW,ZW,ALIW,ZCG,XH,ZH,ALIH,XV,VERTUP,HINAX,
     1                XVF,SCALE,ZV,ZVF,YV,YF,PHIV,PHIF
      COMMON /WHWB/   FACT(182)
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /SUPWBB/  SWB(61),SHB(61)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA
C
      EQUIVALENCE (SHB(2),KKHB), (SHB(11),KBH), (SHB(35),KHB),
     1            (SHB(37),KKBH)
      DIMENSION C(6),ROUTID(2)
      LOGICAL FLAG,VERTUP
      REAL KHB,KBH,KKHB,KKBH
      DATA ROUTID /4HCLWB, 4HT   /
C
      IY = 0
      DO 1000 J=1,NALPHA
         FLAG = ABS(CLBW(J)) .NE. UNUSED
         IF(FLAG) CLBWV(J) = CLBW(J)
         IF(ABS(CLB(J))  .NE. UNUSED) CLBV(J) = CLB(J)
C
         FLAG = ABS(CLBW(J)) .NE. UNUSED .AND. ABS(CLH(J)) .NE. UNUSED
     1    .AND. ABS(QOQI(J)) .NE. UNUSED .AND. ABS(EPS(J)) .NE. UNUSED
         IF(.NOT. FLAG) GO TO 1000
         ALPT = BHT(J+22)-EPS(J)
         FLAG = ABS(DEODA(J)) .NE. UNUSED
         IF(FLAG) CLABWH(J) = CLABW+(KHB+KBH)*CLAH*
     1           (1.0-DEODA(J))*QOQI(J)
         IF(FLAG) CLABWT(J) = CLABWH(J)
         CALL TBFUNX(ALPT,CLHJ,DYDX,NALPHA,FLC(23),CLH,C,IY,
     1              MI,NG,0,0,4HCLH ,1,ROUTID)
         CLI = CLAH*ALIH
         CLBWH(J) = (CLHJ-CLI)*(KHB+KBH)+CLI*(KKHB+KKBH)+FACT(141)*
     1             FACT(J+141)*FACT(J+161)*CLAH*ALPT
         CLBWH(J) = CLBWH(J)*QOQI(J)+CLBW(J)
         CLBWT(J) = CLBWH(J)
 1000 CONTINUE
      RETURN
      END
