      SUBROUTINE CSLOPE
C
C     CALCULATE VARIABLE SLOPE FOR WING
C
      COMMON /IHT/    PHT,XU(60),XL(60)
      COMMON /IBW/    PBW,LL
      COMMON /IVT/    PVT,YU(60),YL(60)
      COMMON /WINGI/  WGIN(100)
      COMMON /SYNTSS/ SYNA(19)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /FLOLOG/ DD(6),HTPL
      EQUIVALENCE(ZW,SYNA(3)),(ZH,SYNA(7))
      DIMENSION WGINT(6),C(6),ROUT(2)
      LOGICAL HTPL
      DATA ROUT/4HCSLO, 4HPE   /
C
C     IF NO HORIZONTAL TAIL, RETURN
C
      DO 1000 I=1,6
 1000 WGINT(I)=UNUSED
      IF(.NOT.HTPL)RETURN
      IF(ZH.GT.ZW)GO TO 1010
C
C     HERE FOR HORIZONTAL TAIL BELOW THE WING
C
C     AT THE 0 PERCENT CHORD
C
      IN=0
      IF(WGIN(95).EQ.UNUSED)CALL TBFUNX(0.,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(95).EQ.UNUSED)WGINT(1)=-DYDX
C
C     AT THE 20 PERCENT CHORD
C
      IN=0
      IF(WGIN(96).EQ.UNUSED)CALL TBFUNX(.2,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(96).EQ.UNUSED)WGINT(2)=-DYDX
C
C     AT THE 40 PERCENT CHORD
C
      IN=0
      IF(WGIN(97).EQ.UNUSED)CALL TBFUNX(.4,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(97).EQ.UNUSED)WGINT(3)=-DYDX
C
C     AT THE 60 PERCENT CHORD
C
      IN=0
      IF(WGIN(98).EQ.UNUSED)CALL TBFUNX(.6,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(98).EQ.UNUSED)WGINT(4)=-DYDX
C
C     AT THE 80 PERCENT CHORD
C
      IN=0
      IF(WGIN(99).EQ.UNUSED)CALL TBFUNX(.8,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(99).EQ.UNUSED)WGINT(5)=-DYDX
C
C     AT THE 100 PERCENT CHORD
C
      IN=0
      IF(WGIN(100).EQ.UNUSED)CALL TBFUNX(1.,Y,DYDX,LL,XL,YL,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(100).EQ.UNUSED)WGINT(6)=-DYDX
      GO TO 1020
 1010 CONTINUE
C
C     HERE FOR THE HORIZONTAL TAIL ABOVE THE WING
C
C     AT THE 0 PERCENT CHORD
C
      IN=0
      IF(WGIN(95).EQ.UNUSED)CALL TBFUNX(0.,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(95).EQ.UNUSED)WGINT(1)=DYDX
C
C     AT THE 20 PERCENT CHORD
C
      IN=0
      IF(WGIN(96).EQ.UNUSED)CALL TBFUNX(.2,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(96).EQ.UNUSED)WGINT(2)=DYDX
C
C     AT THE 40 PERCENT CHORD
C
      IN=0
      IF(WGIN(97).EQ.UNUSED)CALL TBFUNX(.4,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(97).EQ.UNUSED)WGINT(3)=DYDX
C
C     AT THE 60 PERCENT CHORD
C
      IN=0
      IF(WGIN(98).EQ.UNUSED)CALL TBFUNX(.6,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(98).EQ.UNUSED)WGINT(4)=DYDX
C
C     AT THE 80 PERCENT CHORD
C
      IN=0
      IF(WGIN(99).EQ.UNUSED)CALL TBFUNX(.8,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(99).EQ.UNUSED)WGINT(5)=DYDX
C
C     AT THE 100 PERCENT CHORD
C
      IN=0
      IF(WGIN(100).EQ.UNUSED)CALL TBFUNX(1.,Y,DYDX,LL,XU,YU,C,IN,MI,
     1   NG,0,0,4HCSLP,1,ROUT)
      IF(WGIN(100).EQ.UNUSED)WGINT(6)=DYDX
 1020 CONTINUE
      DO 1030 I=1,6
         A=WGINT(I)
         IF(A.EQ.UNUSED)GO TO 1030
         WGIN(I+94)=ATAN(A)*RAD
 1030 CONTINUE
      RETURN
      END
