      SUBROUTINE DNPWBT
C
C     THIS ROUTINE YIELDS THE FOLLOWING WING-BODY-TAIL DERIVATIVES-
C       SUB,TRAN,SUPERSONIC  -CLQ
C                             CMQ
C                             CLADOT
C                             CMADOT
C
      REAL MACH,INFACT,KHB,KBH,LAMDA
      COMMON /OVERLY/ NLOG,NMACH,IM,NALPHA
      COMMON /FLGTCD/ FLC(93)
      COMMON /OPTION/ SREF,CBARR,RUFF,BLREF
      COMMON /SYNTSS/ SYNA(19)
      COMMON /WINGI/  WINGIN(77)
      COMMON /HTI/    HTIN(131)
      COMMON /IBW/    PBW,BW(380)
      COMMON /IBWH/   PBWH,BWH(380)
      COMMON /WINGD/  A(195),B(49)
      COMMON /SUPWBB/  SWB(61),SHB(61)
      COMMON /WBHCAL/ WBT(155)
      COMMON /IDWASH/ PDWASH,DWASH(60)
      COMMON /IWING/  PWING,WING(400)
      COMMON /IHT/    PHT,HT(380)
      COMMON /HTDATA/ AHT(195)
      COMMON /SBETA/  STB(135),TRA(108)
      COMMON /BDATA/  BD(762)
      COMMON /IVT/    PVT,VT(380)
      COMMON /IVF/    PVF,VF(380)
      COMMON/IBWHV/   PBWHV,BWHV(380)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB
      DIMENSION ROUTID(2)
      DIMENSION WTYPE(4)
      DIMENSION CLQWBT(20),CMQWBT(20),CLDWBT(20),CMDWBT(20)
      DIMENSION DTJ(20),GOGOO(20),DEDA(20)
      EQUIVALENCE(CLQWB,BW(201)),(CMQWB,BW(221)),(CLADWB,BW(241)),
     1           (CMADWB,BW(261))
      EQUIVALENCE(LAMDA,A(27))
      EQUIVALENCE(SBW,WINGIN(4)),(BH,HTIN(4)),(XCG,SYNA(1))
      EQUIVALENCE(XH,SYNA(6))
      EQUIVALENCE(CLQWBT(1),BWH(201)),(CMQWBT(1),BWH(221)),
     1           (CLDWBT(1),BWH(241)),(CMDWBT(1),BWH(261))
      DATA WTYPE/4HSTRA,4HDOUB,4HCRAN,4HCURV/
      DATA ROUTID/4HDNPW,4HBT  /
C
      PI=4.*ATAN(1.)
      RAD=180./PI
      TYPE=WINGIN(15)
      ASTRW=A(7)
      MACH=FLC(IM+2)
      IF(SUBSON)BETA=B(2)
      IF(SUPERS)BETA=SWB(6)
      IF(.NOT.SUBSON.AND.(MACH.LT.1.))BETA=SQRT(1.-MACH**2)
      IF(.NOT.SUPERS.AND.(MACH.GT.1.))BETA=SQRT(MACH**2-1.)
      IF(MACH.EQ.1.)BETA=0.
      IF(SUPERS)GO TO 1010
      IF(TRANSN)GO TO 1030
      KHB=WBT(1)
      KBH=WBT(2)
      DXAC=BD(63)
      DO 1000 I=1,NALPHA
         DTJ(I)=WBT(25+I)
         GOGOO(I)=DWASH(I)
         DEDA(I)=DWASH(I+40)
 1000 CONTINUE
      CLAH=HT(101)
      GO TO 1050
 1010 KHB=SHB(35)
      KBH=SHB(11)
      DXAC=BD(63)
      DO 1020 I=1,NALPHA
         DTJ(I)=WBT(I+25)
         GOGOO(I)=DWASH(I)
         DEDA(I)=DWASH(I+40)
 1020 CONTINUE
      CLAH=HT(101)
      GO TO 1050
 1030 DXH=(BH-HTIN(3))*AHT(62)*COS(SYNA(8)/RAD)
      DXCGH=XCG-(XH+DXH)
      DXAC=DXCGH-AHT(30)+AHT(16)/2.
      KBH=SHB(35)
      KHB=SHB(11)
      DO 1040 I=1,NALPHA
      DTJ(I)=0.0
      GOGOO(I)=DWASH(I)
      DEDA(I)=DWASH(I+40)
      CLAH =HT(101)
 1040 CONTINUE
 1050 BWBH=SBW/BH
      DXOCB=-DXAC/CBARR
      BA=BETA*ASTRW
      IF(BWBH.LT.1.5)GO TO 1080
      IF(TYPE.NE.WTYPE(1))GO TO 1120
      IF(BA.LT.0.0 .OR. BA.GT.4. .AND. .NOT.SUPERS)A(13) = 0.0
      DO 1060 I=1,NALPHA
         SAVTIM=2.*(KBH+KHB)*GOGOO(I)*DXOCB
         SAVTIM=SAVTIM*CLAH
         SAVTIX=SAVTIM*DXOCB
         STORE1=CLQWB+SAVTIM
         STORE2=CMQWB-SAVTIX
C
C     ---WING-BODY-TAIL PITCHING DERIVATIVES,CLQ,CMQ---
C
C    BW/BH .GE. 1.5
C    SET V.T. INCREMENTS TO ZERO
C
      VT(I+200) = 0.0
      VT(I+220) = 0.0
      VT(I+240) = 0.0
      VT(I+260) = 0.0
      VF(I+200) = 0.0
      VF(I+220) = 0.0
      VF(I+240) = 0.0
      VF(I+260) = 0.0
      CLQWBT(I)=STORE1
      CMQWBT(I)=STORE2
C
C     ---WING-BODY-TAIL ACCELERATION DERIVATIVES,CLAD,CMAD---
C
      IF(LAMDA .NE. 0.0) A(13) = 1.0
      CLDWBT(I)=CLADWB+SAVTIM*DEDA(I)
 1060 CMDWBT(I)=CMADWB-SAVTIX*DEDA(I)
C
C   IOM B-W-H-V DATA SET IDENTICAL TO B-W-H SINCE ALL VERTICAL
C       TAIL INCREMENTS ARE ZERO
C
      DO 1070 I=1,NALPHA
         BWHV(I+200) = BWH(I+200)
         BWHV(I+220) = BWH(I+220)
         BWHV(I+240) = BWH(I+240)
         BWHV(I+260) = BWH(I+260)
 1070 CONTINUE
      GO TO 1120
 1080 IF(TYPE.NE.WTYPE(1))GO TO 1100
      DO 1090 I=1,NALPHA
      SAVE=2.*(KBH+KHB)*GOGOO(I)*CLAH
      IF(BA.LT.0.0.OR.BA.GT.4.) A(13) = 0.0
C
C    BW/BH .LT. 1.5
C    SET V.T. INCREMENTS TO ZERO
C
      VT(I+200) = 0.0
      VT(I+220) = 0.0
      VF(I+200) = 0.0
      VF(I+220) = 0.0
      CLQWBT(I)=CLQWB+(SAVE+DTJ(I))*DXOCB
      CMQWBT(I)=CMQWB-(SAVE+DTJ(I))*DXOCB**2
C
C   IOM B-W-H-V DATA SET IDENTICAL TO B-W-H SINCE ALL VERTICAL
C       TAIL INCREMENTS ARE ZERO
C
      BWHV(I+200) = BWH(I+200)
      BWHV(I+220) = BWH(I+220)
 1090 CONTINUE
 1100 IF(TRANSN)GO TO 1120
      IF(LAMDA.NE.0.)GO TO 1120
      DXOCB=DXOCB*2.
      DXOCB2=DXOCB**2/2.
      DO 1110 I=1,NALPHA
C
C   BW/BH .LT. 1.5
C   SET V.T. INCREMENTS TO ZERO
C
         VT(I+240) = 0.0
         VT(I+260) = 0.0
         VF(I+240) = 0.0
         VF(I+260) = 0.0
         CLDWBT(I)=CLADWB-DXOCB*DTJ(I)
         CMDWBT(I)=CMADWB+DXOCB2*DTJ(I)
C
C   IOM B-W-H-V DATA SET IDENTICAL TO B-W-H SINCE ALL VERTICAL
C       TAIL INCREMENTS ARE ZERO
C
         BWHV(I+240) = BWH(I+240)
         BWHV(I+260) = BWH(I+260)
 1110 CONTINUE
 1120 CONTINUE
      RETURN
      END
