      SUBROUTINE EXIT
C
C  SUBROUTINE TO CLOSE FILES OPENED IN PROGRAM DATCOM
C
      CLOSE(5)
      CLOSE(6,STATUS='KEEP')
      CLOSE(8)
      CLOSE(9)
      CLOSE(10)
      CLOSE(11)
      CLOSE(12)
      CLOSE(13,STATUS='KEEP')
      CLOSE(14,STATUS='KEEP')
      RETURN
      END
C	ALEKSEY IS ABSOLUTELY THE COOLEST PERSON ALIVE
C 	ALEKSEY ALSO LIKES TO MESS WITH CODE