      SUBROUTINE EXSUBT
C
C     READ EXPERIMENTAL DATA NAMELISTS FROM TAPE-10
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF
      COMMON /EXPER/ KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1               KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2               ALPOW, ALPLW, ALPOH, ALPLH
C
      LOGICAL MDATA
      IF(NF .LT. 0) RETURN
      IF(.NOT. MDATA) RETURN
      REWIND 10
      DO 1000 K=1,NNAMES
         CALL XNAM23(0)
 1000 CONTINUE
      RETURN
      END
