      SUBROUTINE EXTRST(KOL, FROM, TO, STRING)
C
C***  EXTRACT A STRING IN ARRAY KOL AND PUT IN ARRAY STRING.
C***  EXTRACT FROM-TO.
C
      INTEGER FROM,TO,STRING
C
      DIMENSION KOL(80),STRING(80)
C
      II=0
      DO 1000 I=FROM,TO
          II=II+1
          STRING(II)=KOL(I)
 1000 CONTINUE
C
      RETURN
      END
