      SUBROUTINE FINDVN(NUMVN, LENVN, INAME, VNAME, DVNAME, NVN, FOUND)
C
C***  FIND MATCHING VARIABLE NAME
C
C***  INPUTS
C
C  NUMVN - NUMBER OF VARIABLE NAMES TO SEARCH
C  LENVN - ARRAY THAT DEFINES THE LENGTH OF EACH VARIABLE NAME
C  INAME - ARRAY THAT DEFINES THE NAME TO COMPARE
C  VNAME - ARRAY THAT CONTAINS ALL OF THE VARIABLE NAMES
C DVNAME - DIMENSION OF VNAME ARRAY
C
C***  OUTPUTS
C
C    NVN - NUMBER OF VARIABLE FOR WHICH THERE IS A MATCH
C  FOUND - .TRUE. IF VARIABLE NAME MATCH FOUND
C
      INTEGER DVNAME,VNAME,BLANK
C
      LOGICAL FOUND
C
      DIMENSION LENVN(NUMVN),INAME(80),VNAME(DVNAME)
C
      DATA BLANK / 4H     /
C
      FOUND=.FALSE.
C
      INDX=1
C
      DO 1020 NVN=1,NUMVN
C
         IF(NVN .GT. 1)INDX=INDX+MAXC
C
         MAXC=LENVN(NVN)
C
         DO 1000 I=1,MAXC
            IF(INAME(I) .NE. VNAME(I+INDX-1))GO TO 1020
 1000    CONTINUE
C
C ... MAKE SURE REST OF NAME IS BLANK, ELSE NOT RIGHT ONE
C
         J=MAXC+1
         DO 1010 I=J,80
            IF(INAME(I) .NE. BLANK)GO TO 1020
 1010    CONTINUE
C
         FOUND=.TRUE.
         GO TO 1030
C
 1020 CONTINUE
C
      NVN=0
C
 1030 CONTINUE
C
      RETURN
      END
