      SUBROUTINE FINDCH(KOL, CHAR, KCOL)
C
C***  SKIP TO CHARACTER CHAR IN ARRAY KOL, KCOL POINTS TO THE COLUMN
C***  THAT THE CHARACTER RESIDES.  IF THE CHARACTER IS NOT FOUND,
C***  KCOL IS SET TO 81.
C
      INTEGER CHAR
C
      DIMENSION KOL(80)
C
 1000 IF(KOL(KCOL) .EQ. CHAR)GO TO 1010
      KCOL=KCOL+1
C
      IF(KCOL .LT. 81)GO TO 1000
C
 1010 CONTINUE
C
      RETURN
      END
