      SUBROUTINE GLOOK(NXG,XAG,XG,NASG,NOING,IG,TG)
C
C     ----THIS IS A GENERAL TABLE LOOKUP SUBROUTINE.
C
      DIMENSION XG(1)
      LOGICAL NOING,NASG
      DO 1000 I=1,NXG
         II=I
         TEMG=XAG-XG(I)
         DMG=XAG
         IF(XAG .EQ. 0.)DMG=XG(I)
         IF(ABS(DMG) .LE. 0.0001)DMG=1.
         ERG=ABS(TEMG/DMG)
         IF(ERG.LT.1.E-3)GO TO 1010
C
C     ----1ST TEST FOR ASCENDING ORDER. 2ND FOR DESCENDING.
C
         IF(NASG.AND.TEMG.LT.0.)GO TO 1020
         IF(.NOT.NASG.AND.TEMG.GT.0.)GO TO 1020
         TEMPG=TEMG
 1000 CONTINUE
 1010 NOING=.TRUE.
 1020 IG=II
      IF(II .EQ. 1)NOING=.TRUE.
      IF(.NOT. NOING)TG=TEMPG/(TEMPG-TEMG)
      RETURN
      END
