      SUBROUTINE HORTYW
C
C***  EXECUTIVE FOR HORIZONTAL TAIL AND HORIZONTAL TAIL-BODY YAW
C     DERIVATIVES
C
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1        HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /IHT/    PHT,HT(380)
      COMMON /IBH/    PBH,BH(380)
      COMMON /IBW/    PBW,BW(380)
      COMMON /IBWH/   PBWH,BWH(380)
      COMMON /IBWV/   PBWV,BWV(380)
      COMMON /IBWHV/  PBWHV,BWHV(380)
      COMMON /IVT/    PVT,VT(380)
      COMMON /WINGI/  WGIN(4)
      COMMON /HTI  /  HTIN(4)
C
      IF(.NOT. (SUBSON .OR. SUPERS)) GO TO 1030
      IF(SUBSON) CALL SUBHYW
      IF(SUPERS) CALL SUPHYW
C
C     METHODS SAME FOR H.T. OR H.T.-BODY
C
      DO 1020 J=1,NALPHA
         BH(J+300)=HT(J+300)
         BH(J+320)=HT(J+320)
         IF(J .GT. 1 .AND. SUPERS) GO TO 1000
         IF((WGIN(4)/HTIN(4)) .GE. 1.5) HT(J+280)=.5*HT(J+280)
         BH(J+280)=HT(J+280)
         BWH(J+280)=BW(J+280)+HT(J+280)
         IF(SUBSON) GO TO 1020
         GO TO 1010
 1000    BH(J+280)= -UNUSED
         HT(J+280)= -UNUSED
         BWH(J+280)= -UNUSED
 1010    BH(J+340)= UNUSED
         HT(J+340)= UNUSED
 1020 CONTINUE
 1030 CONTINUE
      RETURN
      END
