      SUBROUTINE INFTGM
C
C***  CALCULATE DOWNWASH SYNTHESIZING DIMENSIONS
C
      COMMON /WINGI/  CHRDTP,SSPNOP,SSPNE,SSPN,CHRDBP,CHRDR,SAVSI,SAVSO,
     1                CHSTAT,ALPHAO,TWISTA,SSPNDD,DHDADI,DHDADO,TYPE,
     2                TOVC,DELTAY,XOVC,CLI,ALPHAI,CLALPA(20),
     3                CLMAX(20),CMO,LERI,LERO,CAMBER,TOVCO,XOVCO,CMOT,
     4                CLMAXL,CLAMO,TCEFF,KSHARP,SLOPE(6)
      COMMON /WINGD/  A(195)
      COMMON /HTDATA/ ATH(195)
      COMMON /HTI/    HTIN(154)
      COMMON /CONSNT/ CONST(4)
      COMMON /SYNTSS/ XCG,XW,ZW,ALIW,ZCG,XH,ZH,ALIH,XV,VERTUP,HINAX,
     1                XVF,SCALE,ZV,ZVF,YV,YF,PHIV,PHIF
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT
      LOGICAL         FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT
      LOGICAL LOGCOM(10),VERTUP
      EQUIVALENCE (LOGCOM(1),FLTC)
      EQUIVALENCE (RAD,CONST(4)),(UNUSED,CONST(3))
C
      IF(.NOT.HTPL) GO TO 1010
      COSAIW=COS(ALIW/RAD)
      COSAIH=COS(ALIH/RAD)
      SINAIH=SIN(ALIH/RAD)
      SINAIW=SIN(ALIW/RAD)
      TANAIW=SINAIW/COSAIW
      IF(HINAX .EQ. UNUSED) GO TO 1000
      ZH=ZH+SINAIH*(HINAX-XH)
      XH=HINAX*(1.-COSAIH)+XH*COSAIH
 1000 XBRSTH=ATH(30)-ATH(16)/4.
      DXSTAR=(HTIN(4)-HTIN(3))*ATH(62)
      DXBH=XBRSTH+DXSTAR
      A(193)=XH-XW-CHRDR*COSAIW
      A(194)=A(193)+DXBH*COSAIH
      ZPH=ZH-DXBH*SINAIH-ZW+CHRDR*SINAIW
      DLH=ZPH*TANAIW
      A(24)=(A(194)-DLH)*COSAIW
      A(22)=CHRDR-A(195)
      A(9)=A(29)+(SSPN-SSPNE)*A(38)
      DHH1=ZPH/COSAIW
      DHH2=(A(194)-DLH)*SINAIW
      A(12)=DHH1+DHH2
      A(11)=ATAN(A(12)/A(24))
 1010 CONTINUE
C
C     ----DETERMINE LOCATION OF ZERO SWEEP ANGLE
C
      IF(A(52).LT.0.) GO TO 1020
      A(8)=1.
      RETURN
 1020 IF(A(112).NE.UNUSED) GO TO 1030
C
C     ----HERE IF INBOARD ONLY
C
      A(8)=A(110)/A(13)+CHSTAT
      RETURN
C
C     ----HERE IF INBOARD + OUTBOARD
C
 1030 IC=34
      DO 1050 I=1,3
         CP=I-1
         IF(ABS(A(IC)).GT.1.E-3) GO TO 1040
         A(8)=.25*CP
         RETURN
 1040    IP=IC
         IC=IC+6
         IF(A(IP).GT.0.0.AND.A(IC).LT.0.0) GO TO 1060
 1050 CONTINUE
 1060 A(8)= .25*(CP+(CP+1.)*A(IP)/(A(IP)-A(IC)))
      RETURN
      END
