      SUBROUTINE INIZ
C
C  INITIZE FOR REUSE OF THE COMMON BLOCKS
C
      COMMON /CONSNT/PI,DEG,UNUSED,RAD
      COMMON /IBWH/  PBWH, X(47)
      COMMON /IBWHV/ PBWHV, Y(7)
      COMMON /IBH/   PBH, Z(144)
      DO 1000 I=1,144
         Z(I)=UNUSED
         IF(I.GT.47) GO TO 1000
         X(I)=UNUSED
         IF(I.GT.7) GO TO 1000
         Y(I)=UNUSED
 1000 CONTINUE
      RETURN
      END
