      SUBROUTINE INPUTB(I,KOL,NAMORD)
C
C***  SUBROUTINE TO READ NAMELIST USING THE NAMELIST EMULATOR
C
      COMMON /FLGTCD/ NMACH,NALPHA,MACH(20),ALSCHD(20),RNNUB(20),NGH
     1                ,GRDHT(10),PINF(20),STMACH,TSMACH,TR,ALT(20)
     2                ,TINF(20),VINF(20),WT,GAMMA,NALT,LOOP
      COMMON /BODYI/  NX,X(20),S(20),P(20),R(20),ZU(20),ZL(20),
     1                BNOSE,BTAIL,BLN,BLA,DS,ITYPE,METHOD,ELLIP
      COMMON /WINGI/  CHRDTP,SSPNOP,SSPNE,SSPN,CHRDBP,CHRDR,SAVSI,SAVSO,
     1                CHSTAT,ALPHAO,TWISTA,SSPNDD,DHDADI,DHDADO,
     2                TYPE,
     3                TOVC,DELTAY,XOVC,CLI,ALPHAI,CLALPA(20),
     4                CLMAX(20),CMO,LERI,LERO,CAMBER,TOVCO,XOVCO,CMOT,
     5                CLMAXL,CLAMO,TCEFF,KSHARP,XAC(20),ARCL,YCM,CLD,
     6                SLOPE(6),DWASH
      COMMON /HTI/    HTIN(154)
      COMMON /VTI/    VTIN(154),BVP,BV,BDV,BH,SV,VPHITE,VLP,ZP,
     1                VFIN(154)
      COMMON /FLAPIN/ F(116),TTYPE,CFITC,CFOTC,BITC,BOTC,CFITT,CFOTT,
     1                BITT,BOTT,B1,B2,B3,B4,D1,D2,D3,GCMAX,
     2                KS,RL,BGR,DELR
      COMMON /IBW/    PBW(131),TYPEIN,NACAW(80),NPTS,XCORD(50),
     1                YUPPER(50),YLOWER(50)
      COMMON /IBH/    PBH(131),HTYPE,NACAH(80)
      COMMON /IBV/    PBV(131),VTYPE,NACAV(80)
      COMMON /IVF/    PVF(131),VFTYP,NACAF(80)
C
      REAL NT,ME,ISP,LFP
      REAL NTYPE,NDELTA,NPTS,MEAN,ITYPE,JETFLP
      REAL LERI,LERO
      REAL NENGSP,NOPBPE,NENGSJ,JIALOC,JEVLOC,JEALOC,JINLTA,JEANGL,
     1     JEVELO,JESTMP,JELLOC,JETOTP,JERAD,KSHARP
      REAL NMACH,MACH,NALPHA,NGH
      REAL NX,LAFB,METHOD,NALT,LOOP,KS
C
      LOGICAL LAMNRJ
      LOGICAL VERTUP
      LOGICAL CROT,LAMNR
      LOGICAL CAMBER,CAMH,CAMV
C
      DIMENSION TIME(10),FC(10),LAMNRJ(10)
      DIMENSION MEAN(50),THICK(50)
      DIMENSION ALPHAJ(10),ALPHA(20)
      DIMENSION DELTA(10),CPRMEI(10),CPRMEO(10),SCLD(10),SCMD(10)
      DIMENSION DELTAD(10),DELTAL(10),DELTAR(10),DELTAS(10),XSOC(10),
     1          HSOC(10),HDELTA(10)
      DIMENSION DELJET(10),EFFJET(10),CAPINB(10),CAPOUT(10),DOBDEF(10)
      EQUIVALENCE (ALSCHD(1),ALPHA(1))
      EQUIVALENCE (CAMH,HTIN(64)),(CAMV,VTIN(64))
      EQUIVALENCE (DELTA(1),DELTAD(1),F(1)),(PHETE,F(11)),
     1            (CHRDFI,F(12)),(CHRDFO,F(13)),(SPANFI,F(14)),
     2            (SPANFO,F(15)),(NDELTA,F(16)),(FTYPE,F(17)),
     3            (STYPE,F(18)),(SCLD(1),DELTAL(1),F(19)),
     4            (SCMD(1),DELTAR(1),F(29)),(CPRMEI(1),DELTAS(1),F(39)),
     5            (CPRMEO(1),XSOC(1),F(49)),(CB,XSPRME,F(59)),
     6            (TC,HSOC(1),F(60)),(PHETEP,F(61)),(NTYPE,F(62))
      EQUIVALENCE (F(1),ALITD),(F(2),XHL),(F(3),TWOTI),(F(4),CF),
     1            (F(5),HDELTA(1)),(F(15),LAMNR),(F(16),HNDLTA)
      EQUIVALENCE (CMU,F(63)),(DELJET(1),F(64)),
     1            (JETFLP,F(74)),(EFFJET(1),F(75)),(CAPINB(1),F(85)),
     2            (CAPOUT(1),F(95)),(DOBDEF(1),F(105)),(DOBCIN,F(115)),
     3            (DOBCOT,F(116))
C
C***  COMPUTATIONAL BLOCKS
C
      COMMON /CASEID/ IDCSE(74), KOUNT, NAMSV(100), DIM
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB,PLOT
      COMMON /ERROR/  IERR,GONOGO,IEND,DMPALL,DPB,DPA,DPBD,DPAVF,
     1                DPFACT,DPWBT,DPBHT,DPAVT,DPAHT,DPC,DPD,DPWB,
     2                DPCHT,DPDHT,DPDYNH,SAVE,DMPCSE,DPDVT,DPGR,DPLB,
     3                DPPW,DPSTB,DPSBD,DPSLG,DPSWB,DPSTP,DPDWA,DPSTG,
     4                DPSLA,DPTRA,DPEXPD,DPDVF,DPFLP,DPFHG,DPFCM,DPTCD,
     5                DPFLA,DPTRM,DPSPR,DPTRN,DPTRM2,DPHYP,DPDYN,DPJET,
     6                DPHB,DPSHB,DPTRAH,DPSTBH,DPSEC,DPSLAH,DPINPT,
     7                DPFLC,DPOPTN,DPSYN,DPBDIN,DPWGIN,DPVTIN,DPTVT,
     8                DPVFIN,DPHTIN,DPPWIN,DPLBIN,DPF,DPIOM,
     9                DPIBDY,DPIWG,DPIHT,DPIVT,DPIVF,DPIBW,DPIBH,DPIBV,
     A                DPIBWH,DPIBWV,DPITOT,DPIPWR,DPIDWH,LIST
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB,PLOT
      LOGICAL  IERR,GONOGO,IEND,DMPALL,DPB,DPA,DPBD,DPAVF,
     1         DPFACT,DPWBT,DPBHT,DPAVT,DPAHT,DPC,DPD,DPWB,
     2         DPCHT,DPDHT,DPDYNH,SAVE,DMPCSE,DPDVT,DPGR,DPLB,
     3         DPPW,DPSTB,DPSBD,DPSLG,DPSWB,DPSTP,DPDWA,DPSTG,
     4         DPSLA,DPTRA,DPEXPD,DPDVF,DPFLP,DPFHG,DPFCM,DPTCD,
     5         DPFLA,DPTRM,DPSPR,DPTRN,DPTRM2,DPHYP,DPDYN,DPJET,
     6         DPHB,DPSHB,DPTRAH,DPSTBH,DPSEC,DPSLAH,DPINPT,
     7         DPFLC,DPOPTN,DPSYN,DPBDIN,DPWGIN,DPVTIN,DPTVT,
     8         DPVFIN,DPHTIN,DPPWIN,DPLBIN,DPF,DPIOM,
     9         DPIBDY,DPIWG,DPIHT,DPIVT,DPIVF,DPIBW,DPIBH,DPIBV,
     A         DPIBWH,DPIBWV,DPITOT,DPIPWR,DPIDWH,LIST
      LOGICAL TEST
      LOGICAL  EXPSWT,SSAVE,NONE
      LOGICAL  LOGCOM(10)
      INTEGER  DIM
      EQUIVALENCE (LOGCOM(1),FLTC)
C
      DIMENSION XTYPE(4)
      DIMENSION KOL(80),NACAT(4)
      DIMENSION NAMORD(300)
      EQUIVALENCE (TIME(1),F(1)),(NT,F(11)),(FC(1),F(12)),(ALPHAJ(1),
     1             F(21)),(ME,F(31)),(ISP,F(32)),(SPAN,F(33)),
     2             (PHE,F(34)),(GP,F(35)),(CC,F(36)),(LFP,F(37)),
     3             (LAMNRJ(1),F(38))
      DATA XTYPE  /4HSTRA,4HDOUB,4HCRAN,4HCURV/
      DATA NACAT  /4HW   , 4HH   , 4HV   , 4HF   /
      DO 1300 I=1,KOUNT
         ITR=NAMORD(I)
         IF(ITR.GT.15)ITR=ITR-1
C
C     ----TRANSFER TO CORRECT NAMELIST
C
         GO TO (1000,1010,1020,1030,1060,1070,1080,1090,1100,1110,1120,
     1          1130,1140,1150,1160,1170,1200,1230,1240,1250,1260,1270,
     2          1280),ITR
C
C***  READ NAMELIST FLTCON
C
 1000    CALL XNAM1(0)
         IF(TR .LE. UNUSED) TR = 0.0
         IF(TR .GT. UNUSED) TR = 1.0
         IF(STMACH .LT. 0.6) STMACH = 0.6
         IF(STMACH .GT. 0.99) STMACH = 0.99
         IF(TSMACH .LE. UNUSED) TSMACH = 1.40
         IF(TSMACH .LE. 1.01) TSMACH = 1.01
         IF(TSMACH .GT. 1.4) TSMACH = 1.4
         FLTC=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST OPTIONS
C
 1010    CALL XNAM2(0)
         OPTI=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST BODY
C
 1020    CALL XNAM3(0)
         BO=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST WGPLNF
C
 1030    CALL XNAM4(0)
         WGPL=.TRUE.
C
C     ----CHECK FOR TYPE SET IF IN PREVIOUS NAMELIST
C
         DO 1040 L=1,4
            IF(TYPE.EQ.XTYPE(L))GO TO 1300
 1040    CONTINUE
         NXTYPE=TYPE + .5
         IF(TYPE.LT.5.0)GO TO 1050
C
C     ----PRINT ERROR
C
         WRITE(6,1460) TYPE
         NXTYPE=1
 1050    CONTINUE
         GO TO 1300
C
C***  READ NAMELIST WGSCHR
C
 1060    CALL XNAM5(0)
         WGSC=.TRUE.
         GO TO 1300
C
C***  READ NAMLIST SYNTHS
C
 1070    CALL XNAM6(0)
         SYNT=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST HTPLNF
C
 1080    CALL XNAM7(0)
         HTPL=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST HTSCHR
C
 1090    CALL XNAM8(0)
         HTSC=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST VTPLNF
C
 1100    CALL XNAM9(0)
         VTPL=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST VTSCHR
C
 1110    CALL XNAM10(0)
         VTSC=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST PROPWR
C
 1120    CALL XNAM11(0)
         PRPOWR=.TRUE.
         JETPOW=.FALSE.
         GO TO 1300
C
C***  READ NAMELIST JETPWR
C
 1130    CALL XNAM12(0)
         JETPOW=.TRUE.
         PRPOWR=.FALSE.
         GO TO 1300
C
C***  READ NAMELIST LARWB
C
 1140    CALL XNAM13(0)
         LOASRT=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST GRNDEF
C
 1150    CALL XNAM14(0)
         GO TO 1300
C
C***  READ NAMELIST TVTPAN
C
 1160    CALL XNAM15(0)
         TVTPN=.TRUE.
         GO TO 1300
C
C     TEST FOR ASYFLP READ PREVIOUSLY.IF SO NEGATE IT AND READ SYMFLP
C
 1170    IF(.NOT.ASYFP)GO TO 1190
         ASYFP=.FALSE.
         DO 1180 K=1,69
 1180    F(K)=UNUSED
C
C***  READ NAMELIST SYMFLP
C
 1190    SYMFP=.TRUE.
         CALL XNAM16(0)
         GO TO 1300
C
C     TEST FOR SYMFLP READ BEFORE.IF SO NEGATE IT AND READ ASYFLP
C
 1200    IF(.NOT.SYMFP)GO TO 1220
         SYMFP=.FALSE.
         DO 1210 K=1,69
 1210    F(K)=UNUSED
 1220    ASYFP=.TRUE.
C
C***  READ NAMELIST ASYFLP
C
         CALL XNAM17(0)
         GO TO 1300
C
C***  READ NAMELIST HYPEFF
C
 1230    CALL XNAM18(0)
         HYPEF=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST TRNJET
C
 1240    CALL XNAM19(0)
         TRAJET=.TRUE.
         GO TO 1300
C
C***  READ NAMELIST VFPLNF
C
 1250    CALL XNAM20(0)
         VFPL = .TRUE.
         GO TO 1300
C
C***  READ NAMELIST VFSCHR
C
 1260    CALL XNAM21(0)
         VFSC = .TRUE.
         GO TO 1300
C
C***  READ NAMELIST CONTAB
C
 1270    CALL XNAM22(0)
         CTAB = .TRUE.
         GO TO 1300
 1280    READ(9,1400) (KOL(IJ),IJ=1,80)
         DO 1290 IJ=1,80
            IF(KOL(6) .EQ. NACAT(1)) NACAW(IJ)=KOL(IJ)
            IF(KOL(6) .EQ. NACAT(2)) NACAH(IJ)=KOL(IJ)
            IF(KOL(6) .EQ. NACAT(3)) NACAV(IJ)=KOL(IJ)
            IF(KOL(6) .EQ. NACAT(4)) NACAF(IJ)=KOL(IJ)
 1290    CONTINUE
         IF(KOL(6) .EQ. NACAT(1)) WGSC=.TRUE.
         IF(KOL(6) .EQ. NACAT(2)) HTSC=.TRUE.
         IF(KOL(6) .EQ. NACAT(3)) VTSC=.TRUE.
         IF(KOL(6) .EQ. NACAT(4)) VFSC=.TRUE.
 1300 CONTINUE
      IF(.NOT.BO)GO TO 1370
C
C  CHECK BODY INPUTS TO MEET SPECIFICATIONS NOTED ABOVE
C  IN READING BODY NAMELIST DATA
C
      NNX=NX+0.5
      IF(ELLIP.EQ.0.)ELLIP=UNUSED
      IF(ELLIP.EQ.UNUSED) ELLIP=1.0
      IF(R(1).NE.UNUSED .AND. S(1).EQ.UNUSED .AND. P(1).EQ.UNUSED)
     1   GO TO 1310
      IF(S(1).NE.UNUSED .AND. R(1).EQ.UNUSED .AND. P(1).EQ.UNUSED)
     1   GO TO 1330
      IF(R(1).NE.UNUSED .AND. S(1).NE.UNUSED .AND. P(1).NE.UNUSED)
     1   GO TO 1350
C
C  HERE FOR RADIUS OR AREA INPUT WITH ANOTHER VARIABLE.
C  ONLY R OR S OR R,S,P CAN BE USED.  SET THE GONOGO FLAG,
C  WRITE A MESSAGE AND CONTINUE.
C
      GONOGO=.FALSE.
      WRITE(6,1510)
      GO TO 1370
C
C     HALF WIDTH, R, SPECIFIED
C
 1310 DO 1320 K=1,NNX
      S(K)=PI*R(K)**2*ELLIP
      P(K)=2*PI*R(K)*SQRT((ELLIP**2+1.)/2.)
      R(K)=R(K)*SQRT(ELLIP)
 1320 CONTINUE
      GO TO 1370
C
C     CROSS SECTIONAL AREA, S, SPECIFIED
C
 1330 DO 1340 K=1,NNX
      R(K)=SQRT(S(K)/PI)
      P(K)=2.*PI*SQRT((S(K)/ELLIP)*(ELLIP**2+1.)/2./PI)
 1340 CONTINUE
      GO TO 1370
C
C     R, S, AND P ALL SPECIFIED
C
 1350 DO 1360 K=1,NNX
      R(K)=R(K)*SQRT(ELLIP)
 1360 CONTINUE
 1370 CONTINUE
C
C     ----WRITE FINAL OUTPUTS USED.
C
      IF(.NOT. LIST) GO TO 1380
        WRITE(6,1430)
        IF(FLTC)CALL XNAM1(1)
        IF(OPTI)CALL XNAM2(1)
        IF(SYNT)CALL XNAM6(1)
        IF(BO)CALL XNAM3(1)
        IF(WGPL)CALL XNAM4(1)
        IF(WGSC)CALL XNAM5(1)
        IF(HTPL)CALL XNAM7(1)
        IF(HTSC)CALL XNAM8(1)
        IF(VTPL)CALL XNAM9(1)
        IF(VTSC)CALL XNAM10(1)
        IF(VFPL)CALL XNAM20(1)
        IF(VFSC)CALL XNAM21(1)
        IF(TVTPN)CALL XNAM15(1)
        IF(PRPOWR)CALL XNAM11(1)
        IF(JETPOW)CALL XNAM12(1)
        IF(NGH.NE.UNUSED)CALL XNAM14(1)
        IF(LOASRT)CALL XNAM13(1)
        IF(SYMFP)CALL XNAM16(1)
        IF(ASYFP)CALL XNAM17(1)
        IF(HYPEF)CALL XNAM18(1)
        IF(TRAJET)CALL XNAM19(1)
 1380 CONTINUE
      IF(WGPL.AND.TYPE.EQ.UNUSED)NXTYPE=1
      IF(WGPL) TYPE     = XTYPE(NXTYPE)
      IF(HTPL) NXTYPE   = HTIN(15)+0.5
      IF(HTPL.AND.TYPE.EQ.0)NXTYPE=1
      IF(HTPL) HTIN(15) = XTYPE(NXTYPE)
      IF(VTPL) NXTYPE   = VTIN(15)+0.5
      IF(VTPL.AND.TYPE.EQ.0)NXTYPE=1
      IF(VTPL) VTIN(15) = XTYPE(NXTYPE)
      IF(VFPL) NXTYPE   = VFIN(15)+0.5
      IF(VFPL.AND.TYPE.EQ.0)NXTYPE=1
      IF(VFPL) VFIN(15) = XTYPE(NXTYPE)
C
C     ----SET SWITCHES FOR SPEED REGIMES
C
      NMCH=NMACH+.5
      DO 1390 I=1,NMCH
         IF(MACH(I).LE.STMACH)SUBSON=.TRUE.
         IF(MACH(I).GE.TSMACH)SUPERS=.TRUE.
         IF(MACH(I).GT.STMACH.AND.MACH(I).LT.TSMACH)TRANSN=.TRUE.
 1390 CONTINUE
      RETURN
C
 1400 FORMAT(80A1)
 1410 FORMAT(1X,80A1)
 1420 FORMAT(1H1,10X,57HTHE FOLLOWING IS A LIST OF ALL INPUT CARDS FOR T
     1HIS CASE./1H0)
 1430 FORMAT(1H1,10X,53HTHE FOLLOWING IS A LIST OF FINAL INPUTS FOR THIS
     1 CASE/1H0)
 1440 FORMAT(66H -ERROR--NUMBER OF NAMELISTS IN A SERIES OF SAVE CASES E
     1XCEEDS 300)
 1450 FORMAT(13H1 END OF JOB.)
 1460 FORMAT(42H ERROR TYPE CANNOT BE GREATER THAN 4.TYPE=,E12.5,
     1 9HSET TO 1.)
 1470 FORMAT(41H0 *** WARNING *** THIS IS A SAVE CASE AND,
     1       38H THE DIMENSION SYSTEM HAS BEEN CHANGED/)
 1480 FORMAT(20H ERROR IN CARD BELOW/1H ,80A1)
 1490 FORMAT(27H ERROR(S),THIS CASE NOT RUN/1H1)
 1500 FORMAT(21H ERROR-THE CARD BELOW/1H ,80A1/53H CONTAINS ILLEGAL VARI
     1ABLE NAME TO BE DUMPED.NAME IS ,30A1)
 1510 FORMAT(47H1***** THE BODY IS NOT ADEQUATELY DEFINED *****,/,
     1 75H IN NAMELIST BODY, ONLY THE FOLLOWING COMBINATIONS OF VARIABLE
     2S CAN BE USED,/,48H FOR A CIRCULAR BODY, SPECIFY X AND R OR X AND
     3S,/,75H FOR AN ELLIPTICAL BODY, SPECIFY X AND R OR X AND S, AND TH
     4E VARIABLE ELLIP,/,59H FOR OTHER BODY SHAPES X, R, S, AND P MUST A
     5LL BE SPECIFIED,/)
      END
