      SUBROUTINE M03O03
C
C***  EXEC FOR OVERLAY 3, SUBSONIC WING DRAG
C
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /WINGD/  A(195),B(49)
      COMMON /WHAERO/ C(51),D(55),CHT(51),DHT(55),DVT(55)
      COMMON /WINGI/  WINGIN(77)
      COMMON /IWING/  PWING,WING(400)
      NOVLY=3
      CALL CDRAG(A,B,D,WINGIN,WING)
      RETURN
      END
