      SUBROUTINE M04O04
C
C***  EXEC FOR OVERLAY 4, SUBSONIC ASYMETRIC BODY AERODYNAMICS
C
      COMMON /IBODY/  PBODY, BODY(400)
      COMMON /OVERLY/ NLOG,NMACH,M,NALPHA,IJKDUM(4),NOVLY
      COMMON /OPTION/ SREF,CBARR,ROUGFC,BLREF
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /FLGTCD/ FLC(93)
      COMMON /WINGD/  A(195)
      COMMON /WINGI/  WINGIN(100)
      COMMON /SUPBOD/ SBD(229)
      COMMON /BODYI/  XNX,X(20),S(20),P(20),R(20),
     1                ZU(20),ZL(20),BNOSE,BTAIL,RLN,RLA,DS
      COMMON /SYNTSS/ XCG,XW,ZW,ALIW,ZCG,XH,ZH,ALIH,XV,VERTUP,HINAX,XVF,
     1                SCALE,ZV,ZVF,YV,YF,PHIV,PHIF
      COMMON /HTI/    HTIN(154)
      COMMON /HTDATA/ AHT(195)
      COMMON /BDATA/  BD(275),BOD(120)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      COMMON /EXPER/  KKK(104),KBODY
C
      LOGICAL KBODY,FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      DIMENSION XS(20),SS(20),PS(20),RS(20),XI(3)
      DIMENSION ZUS(20), ZLS(20)
      DIMENSION C(6), D(6), ROUTID(2)
      DATA ROUTID / 4HM04O, 4H04   /
C
      NOVLY=4
      CALL BODOPT
      CALL EXSUBT
C
      IN = 0
      IF(KBODY) CALL TBFUNX(0.0,BD(62),DYDX,NALPHA,BODY(21),BODY(41),
     1                      C,IN,MI,NG,1,1,4HCM0 ,1,ROUTID)
C
C     CALCULATE CLA, CMA, CYB, CNB, CLB, CN, AND CA
C
      BFACT = CBARR/BLREF
      IN = 0
      IM = 0
      DO 1020 J=1,NALPHA
         IF(J .EQ. 1 .AND. .NOT. KBODY) GO TO 1010
         CALL TBFUNX(FLC(J+22),XX,BODY(J+100),NALPHA,FLC(23),BODY(21),
     1               C,IN,MI,NG,0,0,4HCLAB,1,ROUTID)
         CALL TBFUNX(FLC(J+22),XX,BODY(J+120),NALPHA,FLC(23),BODY(41),
     1               D,IM,MI,NG,0,0,4HCMAB,1,ROUTID)
 1010    CONTINUE
         BODY(J+140) = -BODY(J+100)
         BODY(J+160) = -BFACT*BODY(J+120)
         BODY(J+180) = 0.0
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BODY(J+60) = BODY(J+20)*CA + BODY(J)*SA
         BODY(J+80) = BODY(J)*CA - BODY(J+20)*SA
 1020 CONTINUE
      RETURN
      END
