      SUBROUTINE M05O05
C
C***  EXEC FOR OVERLAY 5, SUBSONIC HORIZONTAL TAIL DRAG
C
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /WHAERO/ C(51),D(55),CHT(51),DHT(55),DVT(55)
      COMMON /HTI/    HTIN(131)
      COMMON /IHT/    PHT,HT(380)
      NOVLY=5
      CALL CDRAG(AHT,BHT,DHT,HTIN,HT)
      RETURN
      END
