      SUBROUTINE M07O07
C
C***  EXEC FOR OVERLAY 7, SUBSONIC WING, WING BODY AERO
C
      COMMON /OVERLY/  IJKDUM(8),NOVLY
C
      NOVLY=7
C
      CALL WBAERO
      CALL WBCD
      RETURN
      END
