      SUBROUTINE M09O11
C
C***  EXEC FOR OVERLAY 9, SUBSONIC WING FLOW FIELDS
C
      COMMON /CONSNT/ CONST(4)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /EXPER/ KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1               KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2               ALPOW, ALPLW, ALPOH, ALPLH
      COMMON /WINGD/  A(195), B(49)
      COMMON /IWING/  PWINF, WING(400)
      COMMON /IDWASH/ PDWASH, DWASHI(60)
      EQUIVALENCE (KDWASH(2),KEPSLN)
      LOGICAL KEPSLN, KDWASH
      NOVLY=9
      CALL DWASH
      IF(KEPSLN) CALL EXSUBT
      CALL DYPRLS(B(46),A(24),A(16),WING(21),A(7),A(11),B(23),
     1            DWASHI(1),NALPHA,KEPSLN)
      IF(KDWASH(1)) CALL EXSUBT
      RETURN
      END
