      SUBROUTINE M11O13
C
C***  EXEC FOR OVERLAY 11, GROUND EFFECTS
C
      COMMON /IBW/     PBW, BW(380)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF,IJKDUM(2),NOVLY
      COMMON /CONSNT/ PI,DEG,UNUSED
      COMMON /FLGTCD/ FLC(93)
      COMMON /SUPWH/  GR(303)
      COMMON /ERROR/  IERR,GONOGO,IEND,DMPALL,DPB,DPA,DPBD,DPFLC,DPFACT,
     1           DPWBT,DPBHT,DPAVT,DPAHT,DPC,DPD,DPWB,DPCHT,DPDHT,DPSYN,
     2           SAVE,DMPCSE,DPDVT,DPGR,DPLB,DPPW,DPSTB,DPSBD,DPSLG,
     3           DPSWB,DPSTP,DPDWA,DPSTG,DPSLA,DPTRA,DPEXPD
      LOGICAL    IERR,GONOGO,IEND,DMPALL,DPB,DPA,DPBD,DPFLC,DPFACT,
     1           DPWBT,DPBHT,DPAVT,DPAHT,DPC,DPD,DPWB,DPCHT,DPDHT,DPSYN,
     2           SAVE,DMPCSE,DPDVT,DPGR,DPLB,DPPW,DPSTB,DPSBD,DPSLG,
     3           DPSWB,DPSTP,DPDWA,DPSTG,DPSLA,DPTRA,DPEXPD
      NOVLY=11
      DO 1000 J=1,303
 1000 GR(J)=UNUSED
      CALL GRDEFF(FLC(IG+63),NF)
      IF(DPGR.OR.DMPCSE)CALL DMPARY(GR,303,2HGR,2)
      RETURN
      END
