      SUBROUTINE M12O14
C
C***  EXEC FOR OVERLAY 12, PRINT OUTPUTS
C
      COMMON /OVERLY/  IJKDUM(8),NOVLY
      COMMON /LEVEL2/ SECOND(23)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB,PLOT
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB,PLOT
C
      EQUIVALENCE (DOL2,SECOND(16))
      LOGICAL DOL2
      NOVLY=12
      CALL OUTPUT
      IF(PART .OR. DOL2) CALL AUXOUT
      IF(PLOT) CALL WPLOT
      RETURN
      END
