      SUBROUTINE M13O15
C
C***  EXEC FOR OVERLAY 13, PROPELLER POWER EFFECTS
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /IPOWER/ PP, POWER(200)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /FLGTCD/ FLC(93)
      DIMENSION CR(6), DR(6), ROUTID(2)
      DATA ROUTID / 4HM10O, 4H12   /
      NOVLY=13
      CALL PRPWEF(I)
C
C     CALCULATE CN, CA, CLA, AND CMA INCREMENTS
C
      IN = 0
      IM = 0
      DO 1000 J=1,NALPHA
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         POWER(J+60) = POWER(J+20)*CA + POWER(J)*SA
         POWER(J+80) = POWER(J)*CA - POWER(J+20)*SA
         CALL TBFUNX(FLC(J+22),X,POWER(J+100),NALPHA,FLC(23),POWER(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,POWER(J+120),NALPHA,FLC(23),POWER(41),
     1               DR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
 1000 CONTINUE
      RETURN
      END
