      SUBROUTINE M14O16
C
C***  EXEC FOR OVERLAY 14, LOW ASPECT RATIO AERO
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /CONSNT/ CONST(4)
      COMMON /IBW/    PBW,BW(380)
      COMMON /FLGTCD/ FLC(93)
      DIMENSION CR(6), DR(6), ROUTID(2)
      EQUIVALENCE     (CONST(4),RAD)
      DATA ROUTID / 4HM14O, 4H16   /
      NOVLY=14
      CALL LOARWB
C
C     CALCULATE CN, CA, CLA, AND CMA INCREMENTS
C
      IN = 0
      IM = 0
      DO 1000 J=1,NALPHA
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BW(J+60) = BW(J+20)*CA + BW(J)*SA
         BW(J+80) = BW(J)*CA - BW(J+20)*SA
         CALL TBFUNX(FLC(J+22),X,BW(J+100),NALPHA,FLC(23),BW(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,BW(J+120),NALPHA,FLC(23),BW(41),
     1               DR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
 1000 CONTINUE
      RETURN
      END
