      SUBROUTINE M15O17
C
C***  EXEC FOR OVERLAY 15, SUBSONIC WING LIFT
C
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /WINGD/  A(195),B(49)
      COMMON /IWING/  PWING,WING(400)
      COMMON /WINGI/  WINGIN(77)
      NOVLY=15
      CALL CALCA0(A,B,WINGIN)
      CALL WTLIFT(A,B,WINGIN,WING)
      CALL LIFTCF(A,B,WINGIN,WING)
      RETURN
      END
