      SUBROUTINE M16O20
C
C***  EXEC FOR OVERLAY 16, SUBSONIC HORIZONTAL TAIL LIFT
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /WINGI/  WINGIN(77)
      COMMON /IDWASH/ PDWASH,DWASH(60)
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /IHT/    PHT,HT(380)
      COMMON /HTI/    HTIN(131)
      COMMON /WINGD/  A(195),B(49)
      NOVLY=16
      CALL CALCA0(AHT,BHT,HTIN)
      CALL WTLIFT(AHT,BHT,HTIN,HT)
      CALL LIFTCF(AHT,BHT,HTIN,HT)
      RETURN
      END
