      SUBROUTINE M18O22
C
C***  EXEC FOR OVERLAY 18, SUPERSONIC WING DRAG
C
      COMMON /OVERLY/  IJKDUM(8),NOVLY
      COMMON /OPTION/ SREF, CBARR, ROUGFC, BLREF
      COMMON /SYNTSS/ XCG, XW, ZW, ALIW, ZCG, XH, ZH, ALIH, XV,
     1                VERTUP, HINAX, XVF, SCALE, ZVT, ZVF, YV, YF,
     2                PHIV, PHIF
      COMMON /WINGI/  WINGIN(101)
      COMMON /VTI/    VTIN(154), TVTIN(8), VFIN(154)
      COMMON /HTI/    HTIN(154)
      COMMON /WINGD/  A(195), B(49)
      COMMON /HTDATA/ AHT(195), BHT(49)
      COMMON /VTDATA/ AVT(195), AVF(195)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB
      DIMENSION INDX(12)
      DATA INDX/1,2,3,4,5,6,7,119,120,163,167,168/
C
      NOVLY=18
      CALL SETUP1
C
C     ----SET SURFACE GEOMETRY IF PRESENR
C
      IF(WGPL) CALL WTGEOM(A,WINGIN)
      IF(HTPL) CALL WTGEOM(AHT,HTIN)
      IF(VTPL) CALL WTGEOM(AVT,VTIN)
      DO 1000 I=1,12
         II=INDX(I)
         IF(AVT(II).NE.UNUSED)AVT(II)=AVT(II)/2.
 1000 CONTINUE
      IF(VFPL) CALL WTGEOM(AVF,VFIN)
      DO 1010 I=1,12
         II=INDX(I)
         IF(AVF(II).NE.UNUSED)AVF(II)=AVF(II)/2.
 1010 CONTINUE
      AVT(130) = AVT(130)+ZVT
      AVT(133) = AVT(133)+ZVT
      AVT(136) = AVT(136)+ZVT
      AVF(130) = AVF(130)+ZVF
      AVF(133) = AVF(133)+ZVF
      AVF(136) = AVF(136)+ZVF
C
C     ----SET /OPTION/ PARAMETERS IF NOT INPUT
C
      IF(SREF.EQ.UNUSED) SREF=A(4)
      IF(CBARR.EQ.UNUSED) CBARR=A(122)
      IF(ROUGFC.LT.1.0E-10)ROUGFC=1.6E-4
C
      IF(TRANSN)RETURN
      IF(WGPL) CALL SUPDRG
      RETURN
      END
