      SUBROUTINE M19O23
C
C***  EXEC FOR OVERLAY 19, SUPERSONIC BODY AERO
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /IBODY/  PBODY,BODY(400)
      COMMON /OPTION/ SREF,CBARR,ROUGFC,BLREF
      COMMON /FLGTCD/ FLC(93),STMACH,TSMACH,TR
      COMMON /WINGD/  A(195)
      COMMON /WINGI/  WINGIN(100)
      COMMON /SUPBOD/ SBD(229)
      COMMON /BODYI/  XNX,X(20),S(20),P(20),R(20),
     1                ZU(20),ZL(20),BNOSE,BTAIL,RLN,RLA,DS
      COMMON /SYNTSS/ XCG,XW,ZW,ALIW,ZCG,XH,ZH,ALIHXV,VERTUP,HINAX,
     1                XVF,SCALE,ZV,ZVF,YV,YF,PHIV,PHIF
      COMMON /HTI/    HTIN(154)
      COMMON /HTDATA/ AHT(195)
      COMMON /BDATA/  BD(275),BOD(120)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
C
      LOGICAL       FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      DIMENSION CR(6), DR(6), ROUTID(2)
      DIMENSION XS(20),SS(20),PS(20),RS(20),XI(3)
      DATA ROUTID / 4HM19O, 4H23   /
C
      NOVLY=19
      IF(SREF   .EQ. UNUSED) SREF   = A(4)
      IF(CBARR  .EQ. UNUSED) CBARR  = A(122)
      IF(ROUGFC .EQ. UNUSED) ROUGFC = 1.6E-4
      IF(BLREF  .EQ. UNUSED) BLREF  = 2.0*WINGIN(4)
      CALL SYPBOD(I)
      CALL EXSUBT
C
C
      IF(FLC(I+2) .LT. TSMACH) RETURN
C
C      CALCULATE CLA, CMA,CYB, CNB, AND CLB
C
      BFACT = CBARR/BLREF
      IN = 0
      IM = 0
      DO 1000 J=1,NALPHA
         CALL TBFUNX(FLC(J+22),XX,BODY(J+100),NALPHA,FLC(23),BODY(21),
     1               CR,IN,MI,NG,0,0,4HCLAB,1,ROUTID)
         CALL TBFUNX(FLC(J+22),XX,BODY(J+120),NALPHA,FLC(23),BODY(41),
     1               DR,IM,MI,NG,0,0,4HCMAB,1,ROUTID)
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BODY(J+60) = BODY(J+20)*CA + BODY(J)*SA
         BODY(J+80) = BODY(J)*CA - BODY(J+20)*SA
         BODY(J+140) = -BODY(J+100)
         BODY(J+160) = -BFACT*BODY(J+120)
         BODY(J+180) = 0.0
 1000 CONTINUE
      RETURN
      END
