      SUBROUTINE M22O26
C
C***  EXEC FOR OVERLAY 22, SUPERSONIC HORIZONTAL-TAIL AERO
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /IHT/    PHT, HT(380)
      COMMON /CONSNT/ CONST(4)
      COMMON /EXPER/  KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1                KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2                ALPOW, ALPLW, ALPOH, ALPLH
      EQUIVALENCE (CONST(3),UNUSED)
      COMMON /FLGTCD/ FLC(93)
      DIMENSION CR(6), ROUTID(2)
      EQUIVALENCE (KDWASH(2), KEPSLN)
      LOGICAL KEPSLN
      DATA ROUTID / 4HM22O, 4H26   /
      KEY = 0
      IF(KEPSLN) KEY = 1
      NOVLY=22
      CALL SUPLTG(KEY)
C
C     CALCULATE CLA AND CMA
C
      IN = 0
      DO 1000 J=2,NALPHA
         CALL TBFUNX(FLC(J+22),X,HT(J+100),NALPHA,FLC(23),HT(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         HT(J+120) = -UNUSED
 1000 CONTINUE
      RETURN
      END
