      SUBROUTINE M23O27
C
C***  EXEC FOR OVERLAY 23, SUPERSONIC LATERAL STABILITY
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /FLGTCD/ FLC(95)
      COMMON /CONSNT/ PI,DR,UNUSED,RAD
      COMMON /IWING/  PW, WING(400)
      COMMON /IHT/    PHT, HT(380)
      COMMON /IVT/    PVT, VT(380)
      COMMON /IVF/    PVF, VF(380)
      COMMON /IBODY/  PBODY, BODY(400)
      COMMON /IBH/    PBH, BH(380)
      COMMON /IBV/    PBV, BV(380)
      COMMON /IBW/    PBW, BW(380)
      COMMON /IBWH/   PBWH, BWH(380)
      COMMON /IBWV/   PBWV, BWV(380)
      COMMON /IBWHV/  PBWHV, BWHV(380)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB
C
      NOVLY=23
      NALPHA=FLC(2)+0.5
      IF(WGPL) CALL SUPLAT
      IF(HTPL) CALL SUPLAH
      IF(VTPL) CALL SUPLAV
      IF(VFPL) CALL SUPLAF
C
C  CALCULATE V.T. INCREMENTS FOR LATERAL DERIVATIVES
C
      DO 1000 J=2,NALPHA
         WING(J+140) = -UNUSED
         WING(J+160) = -UNUSED
         HT(J+140) = -UNUSED
         HT(J+160) = -UNUSED
         VT(J+140) = -UNUSED
         VT(J+160) = -UNUSED
         VF(J+140) = -UNUSED
         VF(J+160) = -UNUSED
 1000 CONTINUE
C
C  SET IOM FOR CYB, CNB AND CLB
C
      DO 1010 J=2,NALPHA
         BW(J+140) =  -UNUSED
         BW(J+160) = -UNUSED
         BWH(J+140) = -UNUSED
         BWH(J+160) = -UNUSED
         BWV(J+140) = -UNUSED
         BWV(J+160) = -UNUSED
         BWHV(J+140) = -UNUSED
         BWHV(J+160) = -UNUSED
 1010 CONTINUE
      BV(141) = BODY(141) + VT(141) + VF(141)
      BV(161) = BODY(161) + VT(161) + VF(161)
      BV(181) = BODY(181) + VT(181) + VF(181)
      DO 1020 J=2,NALPHA
         BV(J+140) = -UNUSED
         BV(J+160) = -UNUSED
         BV(J+180) = BODY(J+180) + VT(J+180) + VF(J+180)
         BH(J+140) = -UNUSED
         BH(J+160) = -UNUSED
 1020 CONTINUE
      RETURN
      END
