      SUBROUTINE M24O30
C
C***  EXEC FOR OVERLAY 24, TRANSONIC WING AERO AND BODY STABILITY DATA
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /CONSNT/ CONST(4)
      COMMON /IBODY/  PB, BODY(380)
      COMMON /OPTION/ SREF,CBARR,ROUGFC,BLREF
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      LOGICAL       FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      EQUIVALENCE (CONST(3),UNUSED)
C
      NOVLY=24
C
      IF(WGPL) CALL TRANWB
      IF(HTPL) CALL TRANHB
      CALL EXSUBT
C
C     SET BODY IOM
C
      BODY(141) = -BODY(101)
      BODY(161) = -BODY(121)*CBARR/BLREF
      DO 1010 J=1,NALPHA
         BODY(J+60) = UNUSED
         BODY(J+80) = UNUSED
         IF(J .EQ. 1) GO TO 1000
         BODY(J+20)  = -UNUSED
         BODY(J+40)  = -UNUSED
         BODY(J+60)  = -UNUSED
         BODY(J+80)  = -UNUSED
         BODY(J+100) = -UNUSED
         BODY(J+120) = -UNUSED
         BODY(J+140) = -UNUSED
         BODY(J+160) = -UNUSED
 1000    BODY(J+180) = 0.0
 1010 CONTINUE
      CALL TRANCD
      RETURN
      END
