      SUBROUTINE M25O31
C
C***  EXEC FOR OVERLAY 25, TRANSONIC WING, WING-BODY CMA
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      LOGICAL         FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      NOVLY=25
      IF(WGPL) CALL TRANCM
      IF(HTPL) CALL TRHTCM
      IF(BO)   CALL TRACM0
      RETURN
      END
