      SUBROUTINE M26O32
C
C***  EXEC FOR OVERLAY 26, HYPERSONIC BODY AERO
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /IBODY/  PB, BODY(400)
      COMMON /FLGTCD/ FLC(93)
      COMMON /OPTION/ SREF,CBARR,ROUGFC,BLREF
      DIMENSION C1(6),C2(6),ROUTID(2)
      DATA ROUTID/ 4HM26O, 4H32  /
      NOVLY=26
      CALL HYPBOD(I)
      BFACT = CBARR/BLREF
      IN = 0
      IM = 0
      DO 1000 J=1,NALPHA
         CALL TBFUNX(FLC(J+22),X,BODY(J+100),NALPHA,FLC(23),BODY(21),
     1               C1,IN,MI,NG,0,0,4HCLAB,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,BODY(J+120),NALPHA,FLC(23),BODY(41),
     1               C2,IM,MI,NG,0,0,4HCMAB,1,ROUTID)
         BODY(J+140) = -BODY(J+100)
         BODY(J+160) = -BFACT*BODY(J+120)
         BODY(J+180) = 0.0
 1000 CONTINUE
      RETURN
      END
