      SUBROUTINE M28O34
C
C***  EXEC FOR OVERLAY 28, SUPERSONIC WING-BODY-TAIL AERO
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /IBWH/   PBWH, BWH(380)
      COMMON /IBWHV/  PBWHV, BWHV(380)
      COMMON /EXPER/  KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1                KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2                ALPOW, ALPLW, ALPOH, ALPLH
      DIMENSION KEY(3)
      LOGICAL KDWASH
      EQUIVALENCE (KEY(1),KQOQIN), (KEY(2),KEPSLN), (KEY(3),KDEODA)
      NOVLY=28
      CALL EXSUBT
      DO 1000 J=1,3
         KEY(J) = 0
         IF(KDWASH(J)) KEY(J) = 1
 1000 CONTINUE
      CALL SUPWBT(KDEODA,KQOQIN,KEPSLN)
      DO 1010 J=1,NALPHA
         BWHV(J+ 20) = BWH(J+ 20)
         BWHV(J+100) = BWH(J+100)
         BWHV(J+120) = BWH(J+120)
 1010 CONTINUE
      RETURN
      END
