      SUBROUTINE M30O36
C
C***  EXEC FOR OVERLAY 30, JET POWER EFFECTS
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /POWR/   PW(315)
      COMMON /IPOWER/ PP, POWER(200)
      COMMON /FLGTCD/ FLC(93)
      COMMON /CONSNT/ CONST(4)
      EQUIVALENCE(CONST(4),RAD)
      DIMENSION CR(6),CRR(6),ROUTID(2)
      DATA ROUTID/ 4HM30O, 4H36  /
      NOVLY=30
      CALL JETPWE
C
C  SET IOM FOR CLA AND CMA AND BODY AXES CN AND CA
C
      IN = 0
      IM = 0
      DO 1000 J=1,NALPHA
         SA = SIN(FLC(J+22)/RAD)
         CA = COS(FLC(J+22)/RAD)
         POWER(J+60) = POWER(J+20)*CA + POWER(J)*SA
         POWER(J+80) = POWER(J)*CA - POWER(J+20)*SA
         CALL TBFUNX(FLC(J+22),X,POWER(J+100),NALPHA,FLC(23),POWER(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,POWER(J+120),NALPHA,FLC(23),POWER(41),
     1               CRR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
 1000 CONTINUE
      RETURN
      END
