      SUBROUTINE M37O45
C
C***  EXEC FOR OVERLAY 37, FLAP PITCHING MOMENTS
C
      DIMENSION BOC(4)
      LOGICAL ASYFP
      COMMON /CONSNT/ PI,DR,UNUSED,RAD
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IJKDUM(4),NOVLY
      COMMON /HTDATA/ AHT(195)
      COMMON /FLOLOG/ X(20),ASYFP
      COMMON /FLGTCD/ FLC(93)
      COMMON /FLAPIN/ F(69)
      NOVLY=37
      IF(ASYFP.AND.(F(18).EQ.5.))GO TO 1000
      CALL FLAPCM
      RETURN
 1000 RACH=FLC(I+2)
      BETA=SQRT(1.-RACH**2)
      ARG=AHT(68)/BETA
      SB=ATAN(ARG)*RAD
      CALL GDELTA(GDF,GDI,GDO,ETI,ETO,BOC,SB)
      RETURN
      END
