      SUBROUTINE M38O46
C
C***  EXEC FOR OVERLAY 38, SUBSONIC FLAP DRAG AND TRIM AERO
C
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1        HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2        TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /FLAPIN/ F(69)
      COMMON /CONSNT/ CONST(4)
      COMMON /IWING/  PWING, WING(400)
      COMMON /IVT/    PVT, VT(380)
      COMMON /WINGI/  WINGIN(101)
      COMMON /HTI/    HTIN(131)
      EQUIVALENCE (CONST(3),UNUSED)
      NOVLY=38
      IF(TRIM.AND.HTPL.AND.(.NOT.SYMFP ))GO TO 1010
      IF(F(17).LE.6.)CALL DRAGFP
      IF(TRIM)CALL TRIMRT
      VT(301) = WING(251)
      DO 1000 J=2,NALPHA
 1000 VT(J+300) = -UNUSED
      RETURN
C
C     ---- IF CANARD, RETURN
C
 1010 IF(WINGIN(101).GT.2.0) RETURN
      CALL TRIMR2
      VT(301) = WING(251)
      DO 1020 J=2,NALPHA
 1020 VT(J+300) = -UNUSED
      RETURN
      END
