      SUBROUTINE M39O47
C
C***  EXEC FOR OVERLAY 39, PRINT HIGH LIFT AND CONTROL DATA
C
      COMMON /FLAPIN/ F(138)
      COMMON /IBODY/  PBODY,  BODY(400)
      COMMON /IWING/  PWING,  WING(400)
      COMMON /IHT/    PHT,    HT(380)
      COMMON /IVT/    PVT,    VT(380)
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB,PLOT
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB,PLOT
C
      NOVLY=39
      CALL DUMP2
      CALL OUTPT2
      IF(.NOT. PLOT) GO TO 1000
        WRITE(13,1010) F
        WRITE(13,1010)(BODY(J),J=201,400)
        WRITE(13,1010)(WING(J),J=201,400)
        WRITE(13,1010) (HT(J), J=201,380)
        WRITE(13,1010) (VT(J), J=201,380)
 1000 CONTINUE
 1010 FORMAT(1P,10E12.4)
      RETURN
      END
