      SUBROUTINE M40O50
C
C***  EXEC FOR OVERLAY 40, TRANSONIC LATERAL CONTROL/FLAP AERO
C
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /FLOLOG/ LOG(19),SYMFLP,ASYFLP
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /IWING/  PW, WING(400)
      LOGICAL SYMFLP,ASYFLP
      NOVLY=40
      CALL TRNYRL
      IF(ASYFLP) GO TO 1010
      DO 1000 J=1,10
         WING(J+220) = UNUSED
         IF(J .EQ. 1) GO TO 1000
         WING(J+250) = -UNUSED
 1000 CONTINUE
 1010 CONTINUE
      RETURN
      END
