      SUBROUTINE M41O51
C
C***  EXEC FOR OVERLAY 41, SUPERSONIC HIGH LIFT AND CONTROL AERO
C
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /FLAPIN/ F(69)
      COMMON /IWING/  PW, WING(400)
      NOVLY=41
      IF(F(17).NE.5.0.AND.F(17).NE.6.0)CALL SSHING
      DO 1000 J=2,10
         WING(J+250) = -UNUSED
 1000 CONTINUE
      RETURN
      END
