      SUBROUTINE M42O52
C
C***  EXEC FOR OVERLAY 42, HYPERSONIC FLAP AERO
C
      COMMON /IBODY/  PB, BODY(200)
      COMMON /IWING/  PW, WING(200)
      COMMON /IHT/    PHT, HT(200)
      COMMON /IVT/    PVT, VT(200)
      COMMON /FLAPIN/ F(16)
      COMMON /BDATA/  HYP(80)
      COMMON /CONSNT/ CONST(4)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /ERROR/  LL
      LOGICAL LL(46),DMPCSE,DPHYP
      EQUIVALENCE (LL(21),DMPCSE),(LL(46),DPHYP)
      NOVLY=42
      CALL HYPFLP
      IF(DMPCSE .OR. DPHYP) CALL DMPARY(   F, 16,4H   F,4)
      IF(DMPCSE .OR. DPHYP) CALL DMPARY(BODY,200,4HBODY,4)
      IF(DMPCSE .OR. DPHYP) CALL DMPARY(  HT,200,4H  HT,4)
      IF(DMPCSE .OR. DPHYP) CALL DMPARY( HYP, 80,4H HYP,4)
      IF(DMPCSE .OR. DPHYP) CALL DMPARY(  VT,200,4H  VT,4)
      IF(DMPCSE .OR. DPHYP) CALL DMPARY(WING,200,4HWING,4)
C      CALL OUTPT4
      RETURN
      END
