      SUBROUTINE M43O53
C
C***  EXEC FOR OVERLAY 43, DYNAMIC DERIVATIVES
C
      COMMON /CONSNT/ CONST(4)
      COMMON /IWING/  PWING, WING(400)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /WINGD/  A(195),B(49)
      COMMON /WINGI/  WINGIN(101)
      COMMON /POWR/   DYN(213)
      COMMON /IHT/    PHT,HT(380)
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /HTI/    HTIN(154)
      COMMON /BDATA/  BD(300),DYNH(213)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1        HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2        TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM
      EQUIVALENCE (CONST(3),UNUSED)
      NOVLY=43
      IF(HYPERS) GO TO 1020
      CALL CMALPO(A,B,WINGIN,DYN)
      IF(SUBSON .OR. TRANSN)CALL SUBPAW
      IF(SUBSON) GO TO 1000
      IF(TRANSN)CALL SUPPAW
      IF(SUPERS) CALL SUPPAW
      IF(TRANSN .OR. SUPERS) CALL SUPCMQ
 1000 CONTINUE
C
C     ONLY FIRST LOCATION COMPUTED, SET REST TO BLANK
C
      DO 1010 J=2,NALPHA
         WING(J+200) = -UNUSED
         WING(J+220) = -UNUSED
         WING(J+240) = -UNUSED
         WING(J+260) = -UNUSED
 1010 CONTINUE
 1020 CONTINUE
      IF(HYPERS) GO TO 1050
      IF(.NOT. HTPL) GO TO 1050
      CALL CMALPO(AHT,BHT,HTIN,DYNH)
      IF(SUBSON .OR. TRANSN)CALL SUBPAH
      IF(SUBSON) GO TO 1030
      IF(TRANSN)CALL SUPPAH
      IF(SUPERS) CALL SUPPAH
      IF(TRANSN .OR. SUPERS) CALL SUPHMQ
 1030 CONTINUE
C
C     ONLY FIRST LOCATION COMPUTED, SET REST TO BLANK
C
      DO 1040 J=2,NALPHA
         HT(J+200) = -UNUSED
         HT(J+220) = -UNUSED
         HT(J+240) = -UNUSED
         HT(J+260) = -UNUSED
 1040 CONTINUE
 1050 CONTINUE
      RETURN
      END
