      SUBROUTINE M44O54
C
C***  EXEC FOR OVERLAY 44, SUPERSONIC WING ALPHA DOT DERIVS
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /IWING/  PWING,WING(400)
      COMMON /IHT/    PHT,HT(380)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,
     2                SUPERS,SUBSON,TRANSN,HYPERS,
     3                SYMFP,ASYFP,TRIMC,TRIM
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1        HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,
     2        SUPERS,SUBSON,TRANSN,HYPERS,
     3        SYMFP,ASYFP,TRIMC,TRIM
      NOVLY=44
      IF(WGPL)CALL SUPCLD
      IF(HTPL)CALL SUPHLD
C
C  FIRST LOCATION COMPUTED, SET IOM WITH BLANKS
C
      DO 1000 J=2,NALPHA
        WING(J+240) = -UNUSED
        HT(J+240) = -UNUSED
 1000 CONTINUE
      RETURN
      END
