      SUBROUTINE M45O55
C
C***  EXEC FOR OVERLAY 45, WING AND WING-BODY YAW AND ROLL DERIVS
C
      COMMON /OVERLY/  IJKDUM(8),NOVLY
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC
      NOVLY=45
      IF(WGPL)CALL WINGYW
      IF(HTPL)CALL HORTYW
      RETURN
      END
