      SUBROUTINE M51O63
C
C***  EXEC FOR OVERLAY 51, INITIALIZE ARRAYS
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,INITZE,IJKDUM(3),NOVLY
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /POWR/   PW(315)
      NOVLY=51
      IF(INITZE .EQ. 1) CALL INITZ1
      IF(INITZE .EQ. 2) CALL INITZ2
      IF(INITZE .NE. 3) GO TO 1010
      DO 1000 J=1,315
         PW(J) = UNUSED
 1000 CONTINUE
 1010 CONTINUE
      RETURN
      END
