      SUBROUTINE M53O65
C
C***  EXEC FOR OVERLAY 53, SUPERSONIC TRAILING EDGE FLAP ROLL AND
C     YAW AERO
C
      COMMON /OVERLY/ IJKDUM(8),NOVLY
      COMMON /IHT/    PHT,HT(380)
      COMMON/FLAPIN/F(69)
      NOVLY=53
      IF(F(18).NE.3.0)CALL SPRYAW
C
C     CALCULATE DELTAL-DELTAR
C
      DO 1000 J=1,10
         HT(J+200) = F(J+18)-F(J+28)
 1000 CONTINUE
      RETURN
      END
