      SUBROUTINE M56O70
C
C***  EXEC FOR OVERLAY 56, MACH SHADOWING DATA
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,IJKDUM(3),NOVLY
      COMMON /VTDATA/ AVT(195), AVF(195)
      COMMON /SYNTSS/ SYNA(19)
      COMMON /HTI/    HTIN(154)
      COMMON /VTI/    VTIN(154),TVTIN(8),VFIN(154)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
      COMMON/CONSNT/CONST(4)
      EQUIVALENCE (CONST(3),UNUSED),(VERTUP,SYNA(10))
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB
      LOGICAL ABORT,VERTUP,FINUP,FLAG
      DATA A/4H****/
      NOVLY=56
      IG=0
      FINUP=.NOT. VERTUP
      SYNA6=SYNA(6)
      SYNA7=SYNA(7)
      FLAG=VTPL.AND.(VTIN(I+94).EQ.UNUSED).OR.(VTIN(I+114).EQ.UNUSED)
     1     .OR.(VTIN(I+134).EQ.UNUSED)
      IF(FLAG)CALL VTAREA(VTIN,AVT,VERTUP,SYNA(9),SYNA(14))
      FLAG=VFPL.AND.(VFIN(I+94).EQ.UNUSED).OR.(VFIN(I+114).EQ.UNUSED)
     1     .OR.(VFIN(I+134).EQ.UNUSED)
      IF(FLAG)CALL VTAREA(VFIN,AVF,FINUP,SYNA(12),SYNA(15))
      IF(.NOT.HTPL) GO TO 1070
      IF(HTIN(94+I).NE.UNUSED.AND.HTIN(114+I).NE.UNUSED.AND.
     1   HTIN(134+I).NE.UNUSED) GO TO 1070
      CALL BDAREA(ABORT)
      IF(.NOT.ABORT) GO TO 1070
      DO 1020 JK=1,5
 1020 WRITE(6,1030) (A,K=1,32)
 1030 FORMAT(3X,32A4)
      WRITE(6,1040)
 1040 FORMAT(//////)
      WRITE(6,1050)
 1050 FORMAT(8X,42HLATERAL STABILITY DERIVATIVES ARE DELETED ,
     1      43HBECAUSE ALL OR PART OF THE HORIZONTAL TAIL ,
     2      34HEXPOSED ROOT CHORD LIES OFF OF THE,//,8X,
     3      44HFUSELAGE. FOR THIS CASE THE NAMELIST HTPLNF ,
     4      45HPARAMETERS SHB, SEXT, AND RLPH MUST BE INPUT ,
     5      12HBY THE USER.)
      WRITE(6,1040)
      DO 1060 JK=1,5
 1060 WRITE(6,1030) (A,K=1,32)
      IG=1
 1070 CONTINUE
      SYNA(6)=SYNA6
      SYNA(7)=SYNA7
      RETURN
      END
