      SUBROUTINE MAIN05
C
C***  SUBSONIC HIGH LIFT AND CONTROL DEVICES EXECUTIVE
C
      COMMON /FLAPIN/ F(116)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
      LOGICAL FLAG
C
C***  SYMMETRICAL FLAPS
C
      IF(.NOT. SYMFP) GO TO 1010
        JETFLP=F(74)+0.5
        IF(JETFLP .GE. 1) CALL M55O67
        IF(JETFLP .GE. 1) GO TO 1010
        F(16) = F(16)+1.0
        NDELTA = F(16)+0.5
        F(NDELTA) = 0.0
        CALL M36O44
        CALL M37O45
        CALL M38O46
        F(16) = F(16)-1.0
 1010 CONTINUE
C
C***  ASYMETRICAL FLAPS
C
      IF(.NOT. ASYFP) GO TO 1020
        IF(F(18) .EQ. 5.0) CALL M37O45
        CALL M52O64
 1020 CONTINUE
C
C***  ALL MOVEABLE HORIZONTAL TAIL TRIM
C
      FLAG = .NOT.(SYMFP .OR. ASYFP) .AND. (TRIM .AND. HTPL)
      IF(FLAG) CALL M38O46
      RETURN
      END
