      SUBROUTINE MAIN06
C
C***  TRANSONIC HIGH LIFT AND CONTROL DEVICES EXECUTIVE
C
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF
      COMMON /FLGTCD/ FLC(95)
      COMMON /FLAPIN/ F(116)
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
      LOGICAL FLAG
C
C***  FLAP DATA
C
      IF(SYMFP) CALL M36O44
      IF(.NOT. ASYFP) GO TO 1000
        CALL M52O64
        FLAG = (F(18) .EQ. 5.0) .AND. (FLC(I+2) .LT. 1.0)
        IF(FLAG) CALL M37O45
 1000 CONTINUE
      CALL M40O50
      RETURN
      END
