      SUBROUTINE MAIN02
C
C***  SUBSONIC GROUND EFFECTS DATA EXECUTIVE
C
      COMMON /FLGTCD/ FLC(93), STMACH, TSMACH, TR
      COMMON /FLAPIN/ F(116)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF
C
C***  FLAP AND GROUND HEIGHT LOOPS
C
      NGR = FLC(63)+0.5
      NFP = F(16)+0.5
      IF(NFP .EQ. 0)NFP=1
C
C     THIS WAS DONE IN CASE NFP=0, WITH FTN 77 (V) LOOP DOES NOT EXECUTE
C
      DO 1020 NF=1,NFP
        DO 1010 IG=1,NGR
          CALL M11O13
          CALL M12O14
 1010   CONTINUE
 1020 CONTINUE
      RETURN
      END
