      SUBROUTINE MAIN03
C
C***  TRANSONIC AERO EXECUTIVE
C
      COMMON /FLGTCD/ FLC(160)
      COMMON /WINGI/  WINGIN(101)
      COMMON /HTI/    HTIN(154)
      COMMON /SBETA/  STB(135), TRA(108), TRAH(108), STBH(135)
      COMMON /LEVEL2/ SECOND(23)
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB
C
      LOGICAL DONE, DOL2, FLAG
      EQUIVALENCE (SECOND(15),DONE), (SECOND(16),DOL2)
C
      DATA STRA / 4HSTRA /
C
      DOL2 = ((WINGIN(15) .EQ. STRA) .OR. (.NOT. WGPL)) .AND.
     1       ((HTIN(15)   .EQ. STRA) .OR. (.NOT. HTPL))
      IF(DONE .OR. .NOT. DOL2) GO TO 1020
        NF = -1
        CALL M24O30
 1010   CONTINUE
        CALL M35O43
        IF(NF .GE. -5)                 CALL MAIN01
        IF(NF .EQ. -6 .OR. NF .EQ. -7) CALL MAIN04
        IF(NF .GE. -7)                 GO TO 1010
 1020 CONTINUE
      NF = 1
      IG = 1
      CALL M51O63
      CALL EXSUBT
      CALL M18O22
      IF(.NOT. BO) GO TO 1030
        CALL M06O06
        CALL M19O23
 1030 CONTINUE
      CALL M24O30
      FLAG = BO .AND. (WGPL .OR. HTPL)
      IF(DOL2) CALL M25O31
      CALL EXSUBT
      IF(FLAG) CALL M29O35
      IF(FLAG) CALL M17O21
      CALL M35O43
      CALL M49O61
C
C***  DYNAMIC STABILITY
C
      IF(.NOT. DAMP) GO TO 1040
        IG = 3
        CALL M51O63
        IF(WGPL) CALL M43O53
        CALL M46O56
 1040 CONTINUE
C
C***  PRINT DATA, RETURN TO MAIN00
C
      CALL M12O14
      DOL2 = .FALSE.
      RETURN
      END
