      SUBROUTINE PRCSID
C
C     -----CENTER AND PRINT CASE IDENTIFICATION.
C
      DIMENSION IPR(132)
      LOGICAL LDM,HEAD,LDM2
      COMMON /FLOLOG/ LDM(10),HEAD,LDM2(14)
      COMMON /CASEID/ IDCSE(74)
      DATA IBLNK /4H    /
C
C     ----RETURN IF NO CASE ID CARD.
C
      IF(.NOT.HEAD)RETURN
      KB=0
      DO 1000 I=1,74
         IPR(I)=IBLNK
         IF(IDCSE(I).EQ.IBLNK)GO TO 1000
         KB=KB+1
         IF(KB.EQ.1)IFB=I
         ILB=I
 1000 CONTINUE
      IF(KB.EQ.0) GO TO 1020
C
C     ----CENTER ON PAGE
C
      ICNT=(ILB-IFB+1)/2
      IF=65-ICNT
      K=0
      DO 1010 I=IFB,ILB
         IPR(IF+K)=IDCSE(I)
 1010 K=K+1
      NP=IF+K-1
 1015 WRITE(6,1030)(IPR(I),I=1,NP)
 1020 RETURN
 1030 FORMAT(1X,132A1)
      END
