      SUBROUTINE REPTCT(ICONST, IREPT, IERR)
C
C***  LOOK FOR REPEAT COUNT ON A CONSTANT.  DEFAULT IS 1.
C
      INTEGER BLANK,STAR
C
      DIMENSION ICONST(80),ITCON(80)
C
      DATA STAR  / 4H*    /
      DATA BLANK / 4H     /
C
      IERR=0
      IREPT=1
C
      DO 1000 I=1,80
         ITCON(I)=BLANK
 1000 CONTINUE
C
C***  LOOK FOR *
C
      ICOL=1
      CALL FINDCH(ICONST, STAR, ICOL)
C
      IF(ICOL .LT. 81)GO TO 1010
C
      GO TO 1030
C
C***  BACKUP AND EXTRACT TO *
C
 1010 ICOL=ICOL-1
      CALL EXTRST(ICONST, 1, ICOL, ITCON)
C
C***  CONVERT COUNT TO INTEGER
C
      CALL TOINT(ITCON, IRR, IERR)
      IF(IRR .NE. 0)IREPT=IRR
C
C***  REMOVE REPEAT COUNT FROM STRING
C
      ICOL=ICOL+2
      J=1
      DO 1020 I=ICOL,80
         ICONST(J)=ICONST(I)
         J=J+1
 1020 CONTINUE
C
 1030 CONTINUE
C
      RETURN
      END
