      SUBROUTINE SECLEV
      COMMON /IBODY/  PBO, BODY(400)
      COMMON /IWING/  PWG, WING(400)
      COMMON /IHT/    PHT, HT(380)
      COMMON /IVT/    PVT, VT(380)
      COMMON /IBW/    PBW, BW(380)
      COMMON /IBH/    PBH, BH(380)
      COMMON /IBWHV/  PBT, BWHV(380)
      COMMON /FLGTCD/ FLC(95)
      COMMON /SYNTSS/ XCG,XW,ZW,ALIW,ZCG,XH,ZH,ALIH,XV,VERTUP,HINAX,
     1                XVF,SCALE,ZV,ZVF,YV,YF,PHIV,PHIF
      COMMON /BODYI/  BODYIN(127)
      COMMON /WINGI/  WINGIN(100)
      COMMON /HTI/    HTIN(154)
      COMMON /WINGD/  A(195),B(49)
      COMMON /SBETA/  STB(135),TRA(108),TRAH(108)
      COMMON /BDATA/  BD(762)
      COMMON /WHWB/   FACT(182)
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /SUPWBB/ SWB(61),SHB(61)
      COMMON /LEVEL2/ SEC(23)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA
      COMMON /EXPER/  KLIST,NLIST(100),NNAMES,IMACH,MDATA,KBODY,
     1                KWING,KHT,KVT,KWB,KDWASH(3),ALPOW,ALPLW,
     2                ALPOH,ALPLH
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
C
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART
      LOGICAL DOL2, FLAG
      EQUIVALENCE (SEC(16),DOL2)
C
      IF(.NOT. DOL2) GO TO 1000
      CALL EXSUBT
      IF(WGPL) CALL WINGCL(NALPHA,B(23),ALPOW,ALPLW,TRA(37),
     1         WING(101),TRA(38),WING(21),FLC(I+2),WINGIN(16),
     2         A(35),A(27),A(7),SEC(1),SEC(2),TRA(70),TRA(1),
     3         SEC(17),WING(1),SEC(18),WING(181))
      IF(HTPL) CALL WINGCL(NALPHA,BHT(23),ALPOH,ALPLH,TRAH(37),
     1         HT(101),TRAH(38),HT(21),FLC(I+2),HTIN(16),AHT(35),
     2         AHT(27),AHT(7),SEC(3),SEC(4),TRAH(70),TRAH(1),
     3         SEC(19),HT(1),SEC(20),HT(181))
C
      FLAG = BO .AND. WGPL
      XC = A(161)+XW
      IF(FLAG) CALL WBCLB(NALPHA,WING(21),WING(101),BODY(21),BODY(101),
     1         WING,BODY,BW(101),FLC(23),BD(255),WINGIN,XC,
     2         A(27),ALIW,SWB(35),SWB(11),SEC(6),SEC(9),SEC(5),
     3         TRA(12),FLC(I+2),TRA(6),SWB(2),SWB(37),FACT,
     4         BW(21),BW,BW(181),SEC(21))
      FLAG = BO .AND. HTPL
      XC = AHT(161)+XH
      IF(FLAG) CALL WBCLB(NALPHA,HT(21),HT(101),BODY(21),BODY(101),
     1         HT,BODY,BH(101),FLC(23),BD(255),HTIN,XC,
     2         AHT(27),ALIH,SHB(35),SHB(11),SEC(8),SEC(10),SEC(7),
     3         TRAH(12),FLC(I+2),TRAH(6),SHB(2),SHB(37),FACT(142),
     4         BH(21),BH,BH(181),SEC(22))
C
      FLAG = BO .AND. WGPL .AND. HTPL
      IF(FLAG) CALL WBTCDO
      IF(.NOT. FLAG) BWHV(1) = UNUSED
      IF(.NOT. VTPL) VT(1) = 0.0
      FLAG = BO .AND. (WGPL .OR. HTPL .OR. VTPL)
      IF(FLAG) CALL CDWBT
      IF(FLAG) CALL CLWBT
 1000 CALL CNCA
      RETURN
      END
