      SUBROUTINE SKIPBL(KOL, KCOL)
C
C***  SKIP BLANK CHARACTERS IN ARRAY KOL, UPDATE KCOL POINTER.
C***  KCOL IS SET TO 81 IF ALL LOCATIONS STARTING AT KCOL ARE BLANK.
C
      INTEGER BLANK
C
      DIMENSION KOL(80)
C
      DATA BLANK / 4H     /
C
 1000 IF(KOL(KCOL) .NE. BLANK)GO TO 1010
      KCOL=KCOL+1
C
      IF(KCOL .LT. 81)GO TO 1000
C
 1010 CONTINUE
C
      RETURN
      END
