      SUBROUTINE SWITCH(LG,LXGL,LXGU,XAG,XG,NXG)
C
C     ----THIS SUBROUTINE SETS SWITCHES FOR THE INTERPOLATION-
C     ----EXTRAPOLATION SUBROUTINES
C
      DIMENSION XG(1)
      LOGICAL LG(7)
      DO 1000 I=1,7
         LG(I)=.FALSE.
 1000 CONTINUE
      LG(6)=.TRUE.
      IF(XG(1).GT.XG(NXG))LG(6)=.FALSE.
C
C     ----TEST TO DETERMINE IF EXTRAPOLATION IS REQUIRED.
C
      IF(LG(6))GO TO 1010
C
C     ----HERE FOR DESCENDING XG TABLE
C
      IF(XAG.GT.XG(1))LG(3)=.TRUE.
      IF(XAG.LT.XG(NXG))LG(2)=.TRUE.
      GO TO 1020
C
C     ----HERE FOR ASCENDING XG TABLE
C
 1010 IF(XAG.GT.XG(NXG))LG(2)=.TRUE.
      IF(XAG.LT.XG(1))LG(3)=.TRUE.
 1020 IF(LG(2))GO TO 1030
      IF(.NOT.LG(3))GO TO 1050
      IF(LXGL.GE.0)LG(4)=.TRUE.
      IF(LXGL.LE.0)GO TO 1050
      GO TO 1040
 1030 IF(LXGU.GE.0)LG(4)=.TRUE.
      IF(LXGU.LE.0)GO TO 1050
 1040 LG(5)=.TRUE.
      LG(7)=.TRUE.
 1050 RETURN
      END
