      SUBROUTINE SYNDIM
C
C***  CALCULATES SYNTHESIS DIMENSIONS FOR BODY ANALYSIS
C
      COMMON /BDATA/  BD(762)
      COMMON /WINGI/  CHRDTP,SSPNOP,SSPNE,SSPN,CHRDBP,CHRDR,SAVSI,SAVSO,
     1                CHSTAT,ALPHAO,TWISTA,SSPNDD,DHDADI,DHDADO,TYPE,
     3                TOVC,DELTAY,XOVC,CLI,ALPHAI,CLALPA(20),
     4                CLMAX(20),CMO,LERI,LERO,CAMBER,TOVCO,XOVCO,CMOT,
     5                CLMAXL,CLAMO,TCEFF,KSHARP,SLOPE(6)
      COMMON /WINGD/  A(195)
      COMMON /SYNTSS/ XCG, XW, ZW, ALIW, ZCG, XH, ZH, ALIH, XV,
     1                VERTUP, HINAX, XVF, SCALE, ZV, ZVF, YV,YF,
     2                PHIV, PHIF
      COMMON /HTI/    HTIN(154)
      COMMON /HTDATA/ AHT(195), BHT(49)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
C
      BD(87)=2.*(SSPN-SSPNE)
      BD(78)= SIN(BD(77)/RAD)
      BD(79)= COS(BD(77)/RAD)
      BD(80)= BD(78)/BD(79)
      BD(66)= 0.5*BD(87)*A(62)*BD(79)
      BD(67)= BD(33)-(BD(65)+BD(66))
      A(173)=BD(67)
      BD(68)=BD(74)-BD(65)*BD(80)
      AHT(173) = XCG-(XH+(HTIN(4)-HTIN(3))*AHT(62)*COS(ALIH/RAD))
      RETURN
      END
