      SUBROUTINE TESTOR(KOL,L,NAM,K,IER,LEN,LDM,NUM,NAMES)
C
C***  CHECK IF NAMELIST NAME IS LEGAL INPUT USING NMTEST
C
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
      DIMENSION KOL(1), LEN(1), LDM(1), NAMES(1)
      DIMENSION NUMBER(15)
      LOGICAL END, FLAG, ARRAY, FOUND, NMTEST
      INTEGER BLANK, EQUAL, COMMA
      DATA NUMBER / 4H0   ,4H1   ,4H2   ,4H3   ,4H4   ,
     1       4H5   ,4H6   ,4H7   ,4H8   ,4H9   ,4H+   ,4H-   ,
     2       4H.   ,4H*   ,4HE   /
      DATA END / .TRUE. /
      DATA BLANK / 4H     /, EQUAL / 4H=    /, COMMA / 4H,    /
C
      NA = 0
      NB = 0
      NC = 0
      ND = 0
      NE = 0
      NF = 0
      I  = 0
      IS = 0
C
C***  UNKNOWN NAMELIST NAME - WRITE CARD AND RETURN
C
      IF(IER .EQ. 0) GO TO 1010
        WRITE(6,1170) (KOL(J),J=1,80)
        GO TO 1160
 1010 CONTINUE
C
C***  END CARD - WRITE CARD AND RETURN
C
      IF(NAM .GE. 2) GO TO 1020
        WRITE(6,1180) (KOL(J),J=1,80)
        END = .TRUE.
        GO TO 1160
 1020 CONTINUE
C
C***  INSERT END CARD IF REQUIRED
C
      FLAG = (K .EQ. 1) .AND. (.NOT. END)
      IF(.NOT. FLAG) GO TO 1030
        WRITE(6,1190)  KAND
        WRITE(11,1200) KAND, (BLANK,J=1,75)
        END = .TRUE.
 1030 CONTINUE
C
C***  FIRST CARD DOES NOT CONTAIN NAMELIST NAME - WRITE CARD AND RETURN
C
      FLAG = (K .EQ. 2) .AND. END
      IF(.NOT. FLAG) GO TO 1040
        WRITE(6,1210) (KOL(J),J=1,80), KAND
        GO TO 1160
 1040 CONTINUE
C
C***  TEST FOR VALID VARIABLE NAME STARTING IN KOL(L)
C
      IF(K .EQ. 1) END = .FALSE.
      IF(KOL(L) .NE. BLANK) GO TO 1050
        L = L+1
        IF(L .GE. 81) GO TO 1150
        GO TO 1040
 1050 CONTINUE
      IF(KOL(L) .EQ. KAND) END = .TRUE.
      IF(END) GO TO 1150
      CALL VNAME(KOL,L,LEN,NUM,NAMES,I,FOUND,ARRAY,NDMS,NF,NUMBER,
     1           BLANK,EQUAL)
C
C***  NAME NOT FOUND, IF K=2 CHECK FOR NUMBER CONTINUATION
C***                  IF K=1 SEARCH FOR NEXT NAME
C
      IF(FOUND) GO TO 1090
      IF(K .EQ. 1) GO TO 1070
        NDMS = NDML
        NDML = 0
        DO 1060 J=1,14
        IF(KOL(L) .EQ. NUMBER(J)) GO TO 1120
 1060   CONTINUE
 1070 CONTINUE
      IS = I
      NA = NA+1
 1075 CONTINUE
      IF(L .GE. 81) GO TO 1150
      IF(KOL(L) .EQ. KAND) GO TO 1050
      FLAG = (KOL(L) .EQ. BLANK) .OR. (KOL(L) .EQ. EQUAL) .OR.
     1       (KOL(L) .EQ. COMMA)
      IF(FLAG) GO TO 1077
        L = L+1
        GO TO 1075
 1077 CONTINUE
      IF(L .GE. 81) GO TO 1150
      DO 1080 J=1,15
      IF(KOL(L) .EQ. NUMBER(J)) GO TO 1085
 1080 CONTINUE
      FLAG = (KOL(L) .EQ. BLANK) .OR. (KOL(L) .EQ. EQUAL) .OR.
     1       (KOL(L) .EQ. COMMA)
      IF(FLAG) GO TO 1085
      IF(NMTEST(KOL(L),TRUE,4)) L = L+3
      IF(NMTEST(KOL(L),TRUE,4)) GO TO 1085
      IF(NMTEST(KOL(L),FALSE,5)) L = L+4
      IF(NMTEST(KOL(L),FALSE,5)) GO TO 1085
      IF(KOL(L-1) .EQ. NUMBER(15)) L = L-1
      GO TO 1040
 1085 CONTINUE
      L = L+1
      GO TO 1077
C
C***  NAME FOUND - SET UP ARRAY DESIGNATION AND CHECK NAME DELIMITERS
C
 1090 CONTINUE
      IS = I
      NDM = IABS(LDM(I))
      NDML = 0
      FLAG = ARRAY .AND. (NDM .EQ. 1)
      IF (.NOT. FLAG) GO TO 1100
        ARRAY = .FALSE.
        NC = NC+1
 1100 CONTINUE
      IF(L .GE. 80) GO TO 1110
      IF(KOL(L) .NE. BLANK) GO TO 1110
        L = L+1
        GO TO 1100
 1110 CONTINUE
      IF(KOL(L) .NE. EQUAL) NB = NB+1
      IF(KOL(L) .EQ. EQUAL) L = L+1
C
C***  CHECK NUMERICAL INPUT AND THE NUMBER OF ARRAY
C***  ELEMENTS INPUT
C
 1120 CONTINUE
      I = IS
      IF(I .EQ. 0) GO TO 1075
      IF(L .GE. 81) GO TO 1150
      IF(KOL(L) .NE. BLANK) GO TO 1130
        L = L+1
        GO TO 1120
 1130 CONTINUE
      IF(LDM(I) .LT. 0) CALL LVALUE(KOL,L,NDML,NF,BLANK,
     1                             COMMA,NUMBER)
      IF(LDM(I) .GT. 0) CALL RVALUE(KOL,L,NDML,NF,BLANK,
     1                             COMMA,NUMBER)
C
C***  CHECK THE NUMBER OF VALUES LOADED TO THE VARIABLE DIMENSION
C
      IF(NDML .EQ. 0) GO TO 1077
      IF(NDM .EQ. 1 .AND. NDML .GT. 1) ND = ND+1
      NDML = NDML+NDMS
      IF(NDM .GT. 1 .AND. NDML .GT. NDM) NE = NE+1
      IF(L .LE. 80) GO TO 1040
C
C***  END OF CARD OR END OF INPUT ENCOUNTERED
C
 1150 CONTINUE
      NERR = NA+NB+NC+ND+NE+NF
      IF(NERR .EQ. 0) WRITE(6,1180) (KOL(J),J=1,80)
      IF(NERR .NE. 0) WRITE(6,1220) (KOL(J),J=1,80), NA, NB,
     1                              NC, ND, NE, NF
 1160 WRITE(11,1230) (KOL(J),J=1,80)
C
C***  FORMATS
C
 1170 FORMAT(1X,80A1,3X,33H** ERROR ** UNKNOWN NAMELIST NAME)
 1180 FORMAT(1X,80A1)
 1190 FORMAT(2X,A1,3HEND,78X,32H** MISSING NAMELIST TERMINATION ,
     1       8HADDED **)
 1200 FORMAT(1X,A1,3HEND,75A1)
 1210 FORMAT(1X,80A1,3X,39H** ERROR ** NO NAMELIST NAME FOLLOWING ,A2)
 1220 FORMAT(1X,80A1,3X,11H** ERROR **,I3,2H*A,I3,2H*B,I3,2H*C,
     1       I3,2H*D,I3,2H*E,I3,2H*F)
 1230 FORMAT(80A1)
C
      RETURN
      END
