      SUBROUTINE TRIMR2
C
C***  SUBROUTINE TO TRIM THE VEHICLE WITH AN ALL MOVABLE TAIL
C
      REAL KBW,KWB,KKBW,KKWB,NTRIM
      COMMON /OPTION/ SREF,CBARR,RUFF,BLREF
      COMMON /OVERLY/ NLOG,NMACH,IZ,NALPHA
      COMMON /CONSNT/ PI,DR,UNUSED,RAD
      COMMON /IHT/    PHT, HT(380)
      COMMON /IVT/    PVT, VT(380)
      COMMON /POWR/   PW(293),TRM2(22)
      COMMON /IDWASH/ PDWASH, DWASH(60)
      COMMON /IBW/    PBW, BW(380)
      COMMON /SYNTSS/ SYNA(19)
      COMMON /FLGTCD/ FLC(93)
      COMMON /BDATA/  BD(762)
      COMMON /HTI/    HTIN(154)
      COMMON /HTDATA/ AHT(195),BHT(49)
      COMMON /WBHCAL/ WBT(155)
      COMMON /WHAERO/ XXX(157), DHT(55)
C
      DIMENSION ALPH(20),ALIHT(20),ALPH1(20),ALMEP(20)
      DIMENSION CLHTRM(20),CDHTRM(20),CMHTRM(20),HMTRM(20),HMUNT(20)
     1,CLWBT(20),CDWBT(20),CMWB(20),QOQI(20),ALPHA(20),EPSLON(20)
     2,CLH(20),CLBH(20),CDH(20),CC(6),ROUTID(2)
C
      EQUIVALENCE (ALIHT(1),HT(221)),(HINAX,SYNA(11)),(XCG,SYNA(1))
     1,(CMHTRM(1),HT(281)),(HMTRM(1),HT(301)),(HMUNT(1),HT(201))
     2,(CLWBT(1),VT(221)),(CDWBT(1),VT(201)),(CLHTRM(1),TRM2(1)),
     3 (NTRIM,TRM2(21)),(TSTOP,TRM2(22)),(CDHTRM(1),HT(241))
      EQUIVALENCE (KWB,WBT(1)),(KBW,WBT(2)),(KKWB,WBT(150))
     1,(CMWB(1),BW(41)),(QOQI(1),DWASH(1)),(CLBH(1),WBT(130))
     2,(ALPHA(1),FLC(23)),(XBA,BD(63)),(ZBA,BD(64)),(AR,AHT(7))
     3,(E,DHT(30)),(EPSLON(1),DWASH(21)),(ALIH,SYNA(8)),(CLH(1),HT(21))
     4,(KKBW,WBT(151)),(SSPN,HTIN(4)),(SSPNE,HTIN(3)),(ACLMAX,BHT(43)),
     5 (CDOH,BHT(46)),(CMOH,BHT(47)),(AOH,BHT(49)),(CDOV,WBT(66))
     6,(CLAH,HT(101)),(CDH(1),HT(1))
C
      DATA ROUTID / 4HTRIM, 4HR2   /
C
      TSTOP=1.
      SRATIO=SREF/AHT(3)
      DO 1000 J=1,NALPHA
         ALMEP(J)=ALPHA(J)-EPSLON(J)
         ALPH(J)=ALPHA(J)-EPSLON(J)
 1000 ALPH1(J)=ALMEP(J)+ALIH
      NTRIM=NALPHA
      XBAR=XBA/CBARR
      ZBAR=ZBA/CBARR
      DO 1030 J=1,NALPHA
         JJ=J
         IF(ALMEP(J).GT.ACLMAX)GO TO 1040
         ARGL=-COS(ALMEP(J)/RAD)*XBAR+SIN(ALMEP(J)/RAD)*ZBAR
         ARGD=SIN(ALMEP(J)/RAD)*XBAR+COS(ALMEP(J)/RAD)*ZBAR
         CMWB(J)=BW(J+40)
      IF(CMWB(J).EQ.2.*UNUSED) GO TO 1050
C
C     CHECK TO SEE IF ALPHA IS IN DOWNWASH RANGE OF VALUES
C
         IF(ALPH1(J).GE.(-ACLMAX).AND.ALPH1(J).LE.ACLMAX) GO TO 1020
         ALIHT(J)=-1000.
         CLHTRM(J)=-1000.
         GO TO 1030
C
C     CALCULATE HORIZONTAL TAIL TRIM LIFT, DATCOM EQN. 4.5.3.2-E
C     TRIM LIFT IS RELATIVE TO LOCAL FLOW AT TAIL
C
 1020    CLHNUM=2.*((CMWB(J)+QOQI(J)*CMOH)/(ARGL*QOQI(J))+CDOH*ARGD
     1          /ARGL)
         CLHDEN=1.+SQRT((1.-4.*(ARGD/(ARGL*PI*AR*E)*SRATIO)*
     1          (CLHNUM/2.)))
         CLHTRM(J)=CLHNUM/CLHDEN
         CDHTRM(J)=CDOH+CLHTRM(J)**2/(PI*AR*E)*SRATIO
C
C     CALCULATE STABILIZER INCIDENCE TO TRIM AT ALPHA
C
         BRACKT=WBT(J+67)*WBT(J+45)*(SSPN-SSPNE)/SSPN
         IN=0
         CALL TBFUNX(ALPH(J),CLHP,CLAHP,NALPHA,BHT(23),CLH,CC,IN,MI,
     1               NG,1,1,4HCLH ,1,ROUTID)
         ALIHT(J)=(CLHTRM(J)-(KWB+KBW)*(CLHP+CLAHP*BRACKT*ALPH(J)))/
     1            ((KKWB+KKBW)*(CLAHP+BRACKT*CLAH))
C
C     CALCULATE TRIM LIFT AND DRAG RELATIVE TO BODY FREE STREAM FLOW
C
         EPS=EPSLON(J)/RAD
         ALP=ALPHA(J)/RAD
         DCLTRM=(CLHTRM(J)*COS(EPS)-CDHTRM(J)*SIN(EPS))*QOQI(J)
         DCDTRM=(CDHTRM(J)*COS(EPS)+CLHTRM(J)*SIN(EPS))*QOQI(J)
         CLHTRM(J)=DCLTRM
         CDHTRM(J)=DCDTRM
C
C     CALCULATE OTHER TRIM OUTPUT
C
         HT(J+260)=DCLTRM
         ARGL=COS(ALMEP(J)/RAD)*XBAR+SIN(ALMEP(J)/RAD)*ZBAR
         ARGD=COS(ALMEP(J)/RAD)*ZBAR-SIN(ALMEP(J)/RAD)*XBAR
         CMHTRM(J)=DCLTRM*ARGL+CDHTRM(J)*ARGD
C
C     TRIMMED AND UNTRIMMED HINGE MOMENTS
C
         ARG=(HINAX+XBA-XCG)/CBARR
         HMTRM(J)=(DCLTRM*COS(ALP)+DCDTRM*SIN(ALP))*ARG
         HMUNT(J)=(CLH(J)*COS(ALP)+CDH(J)*SIN(ALP))*ARG
C
C     WING-BODY-TAIL CL AND CD AT TRIM CONDITION
C
         CLWBT(J)=CLHTRM(J)+CLBH(J)+BW(J+20)
         CDWBT(J)=BW(J)+DCDTRM+CDOV
 1030 CONTINUE
      RETURN
 1040 TSTOP=2.
      NTRIM=JJ-1
      RETURN
 1050 TSTOP=3.
      NTRIM=JJ-1
      RETURN
      END
