      SUBROUTINE WBAERO
C
C ***
C
      COMMON /IBODY/   PBODY,  BODY(400)
      COMMON /IWING/   PWING,  WING(400)
      COMMON /IHT/     PHT,    HT(380)
      COMMON /IBW/     PBW,    BW(380)
      COMMON /IBH/     PBH,    BH(380)
      COMMON /IBV/     PBV,    BV(380)
C
      COMMON /FLGTCD/ FLC(160)
      COMMON /OPTION/ SREF, CBARR, ROUGFC, BLREF
      COMMON /SYNTSS/ XCG, XW, ZW, ALIW, ZCG, XH, ZH, ALIH, XV,
     1                VERTUP, HINAX, XVF, SCALE, ZV, ZVF, YV, YF,
     2                PHIV, PHIF
      COMMON /WINGI/  WINGIN(101)
      COMMON /HTI/    HTIN(154)
      COMMON /WINGD/  A(195), B(49)
      COMMON /BDATA/  BD(762)
      COMMON /WHWB/   FACT(182), WB(39), HB(39)
      COMMON /HTDATA/ AHT(195), BHT(49)
      COMMON /WHAERO/ C(51), D(55), CHT(51), DHT(55), DVT(55), DVF(55)
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA,IG,NF,LF,L
      COMMON /EXPER/  KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1                KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2                ALPOW, ALPLW, ALPOH, ALPLH
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2                TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3                HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4                VFPL,VFSC,CTAB
C
      LOGICAL  VERTUP,MDATA,KBODY,KWING,KHT,KVT,KWB,KDWASH
      LOGICAL  FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1         HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON,
     2         TRANSN,HYPERS,SYMFP,ASYFP,TRIMC,TRIM,DAMP,
     3         HYPEF,TRAJET,BUILD,FIRST,DRCONV,PART,
     4         VFPL,VFSC,CTAB,FOUND
C
      DIMENSION CR(6), DR(6), ER(6), FR(6), ROUTID(2)
      DATA ROUTID / 4HM07O, 4H07   /
C
      IF(.NOT. WGPL) GO TO 1010
      DB=BD(87)
      AIW=BD(77)
      COSAIW=BD(79)
      CMOB=BD(62)
      BD(535)=WINGIN(4)-WINGIN(3)
      FACT(1)=BD(535)/WINGIN(4)
      CALL BODOWG(BD(255),BD(83),BD(535),WINGIN(4),A(27),FACT(2),
     1            FACT(22),NALPHA)
C
C     ----COMPUTE WING BODY LIFT,PITCHING MOMENTS AND DRAG.
C
      CALL WBDRAG(A,B,D,BD,WB,BW,BODY,WING,KBODY,KWING)
      CALL WBLIFT(A,B,DB,AIW,WB,BW,FACT,BODY,WING,WINGIN)
      CALL WBCM(A,B,C,DB,XCG,XW,COSAIW,CMOB,WB,BW,BODY,WINGIN,BD(70),
     1         WING(121),ALIW,BD(81),ZW,WING(41),FACT(1),ZCG)
C
C     CALCULATE CLA AND CMA
C
      CALL EXSUBT
      IN = 0
      IM = 0
      NLA=NALPHA
      FOUND=.FALSE.
      DO 900 J=1,NALPHA
         IF(BW(J+40) .NE. 2.*UNUSED .OR. FOUND) GO TO 900
         NLA=J-1
         FOUND=.TRUE.
 900  CONTINUE
      DO 1000 J=1,NALPHA
         CALL TBFUNX(FLC(J+22),X,BW(J+100),NALPHA,FLC(23),BW(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,BW(J+120),NLA,FLC(23),BW(41),
     1               DR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
         IF(J .GT. NLA) BW(J+120)=2.*UNUSED
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BW(J+60) = BW(J+20)*CA + BW(J)*SA
         BW(J+80) = BW(J)*CA - BW(J+20)*SA
 1000 CONTINUE
 1010 IF(.NOT. HTPL) GO TO 1030
      YEXP=HTIN(4)-HTIN(3)
      XC4=AHT(161) + XH
      FACT(142)=(HTIN(4)-HTIN(3))/HTIN(4)
      DB=2.*YEXP
      AIW=ALIH
      COSAIW=COS(ALIH/RAD)
      CMOB=BD(62)
      CMAHT=(BD(63)/CBARR)*HT(101)
      ZAC = ZH-XH*SIN(ALIH/RAD)/COSAIW-CHT(6)*AHT(10)*
     1      SIN(ALIH/RAD)-ZCG
      CALL BODOWG(BD(255),XC4,YEXP,HTIN(4),AHT(27),FACT(143),
     1            FACT(163),NALPHA)
C
C     ----COMPUTE H.T. BODY LIFT,PITCHING MOMENTS AND DRAG.
C
      CALL WBDRAG(AHT,BHT,DHT,BD,HB,BH,BODY,HT,KBODY,KHT)
      CALL WBLIFT(AHT,BHT,DB,AIW,HB,BH,FACT(142),BODY,HT,HTIN)
      CALL WBCM(AHT,BHT,CHT,DB,XCG,XH,COSAIW,CMOB,HB,BH,BODY,HTIN,ZAC,
     1         CMAHT,ALIH,BD(81),ZH,HT(41),FACT(142),ZCG)
C
C     CALCULATE CLA AND CMA
C
      CALL EXSUBT
      IN = 0
      IM = 0
      DO 1020 J=1,NALPHA
         CALL TBFUNX(FLC(J+22),X,BH(J+100),NALPHA,FLC(23),BH(21),
     1               CR,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,BH(J+120),NALPHA,FLC(23),BH(41),
     1               DR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BH(J+60) = BH(J+20)*CA + BH(J)*SA
         BH(J+80) = BH(J)*CA - BH(J+20)*SA
 1020 CONTINUE
 1030 IF( .NOT. (BO .AND. VTPL)) GO TO 1070
C
C     B-V DATA
C
      DO 1050 J=1,NALPHA
         DO 1040 K=1,7
            KK=(K-1)*20
            BV(J+KK)=BODY(J+KK)
            IF(KK .EQ. 0) BV(J+KK)=BODY(J+KK)+DVT(20)+DVF(20)
 1040    CONTINUE
 1050 CONTINUE
C
C     CALCULATE CN, CA, CLA, AND CMA
C
      IN = 0
      IM = 0
      DO 1060 J=1,NALPHA
         CA = COS(FLC(J+22)/RAD)
         SA = SIN(FLC(J+22)/RAD)
         BV(J+60) = BV(J+20)*CA + BV(J)*SA
         BV(J+80) = BV(J)*CA - BV(J+20)*SA
         IF(J .EQ. 1) GO TO 1060
         CALL TBFUNX(FLC(J+22),X,BV(J+100),NALPHA,FLC(23),BV(21),
     1               ER,IN,MI,NG,0,0,4HCLA ,1,ROUTID)
         CALL TBFUNX(FLC(J+22),X,BV(J+120),NALPHA,FLC(23),BV(41),
     1               FR,IM,MI,NG,0,0,4HCMA ,1,ROUTID)
 1060 CONTINUE
 1070 CONTINUE
      RETURN
      END
