      SUBROUTINE WINGYW
C
C *** MAIN LOGIC FOR WING YAW DAMPING DERIVATIVES
C
      COMMON /FLOLOG/ FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1                HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON
      LOGICAL FLTC,OPTI,BO,WGPL,WGSC,SYNT,HTPL,HTSC,VTPL,VTSC,
     1        HEAD,PRPOWR,JETPOW,LOASRT,TVTPAN,SUPERS,SUBSON
      COMMON /OVERLY/ NLOG,NMACH,I,NALPHA
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD
      COMMON /IWING/  PWING,WING(400)
      COMMON /IBW/    PBW,BW(380)
C
      IF(.NOT. (SUBSON .OR. SUPERS)) GO TO 1040
      IF(SUBSON) CALL SUBRYW
      IF(SUPERS) CALL SUPRYW
C
C     METHODS SAME FOR WING OR WING-BODY, NO CNR SUPERSONIC METHODS
C
      DO 1030 J=1,NALPHA
         BW(J+300)=WING(J+300)
         BW(J+320)=WING(J+320)
         IF(J .GT. 1 .AND. SUPERS) GO TO 1010
         BW(J+280)=WING(J+280)
         IF(SUPERS) GO TO 1020
         BW(J+340)=WING(J+340)
         GO TO 1030
 1010    BW(J+280)= -UNUSED
         WING(J+280)= -UNUSED
 1020    BW(J+340)= UNUSED
         WING(J+340)= UNUSED
 1030 CONTINUE
 1040 CONTINUE
      RETURN
      END
