      SUBROUTINE XPERNM
C
C     DEFINE THE NUMBER OF CARDS IN EACH EXPERIMENTAL DATA NAMELIST
C
      COMMON /EXPER/ KLIST, NLIST(100), NNAMES, IMACH, MDATA,
     1               KBODY, KWING, KHT, KVT, KWB, KDWASH(3),
     2               ALPOW, ALPLW, ALPOH, ALPLH
      COMMON /CONSNT/ PI,DEG,UNUSED,RAD,KAND
      LOGICAL FIRST, TEST
      DIMENSION KOL(80), KEXP(4)
      DATA KEXP / 1HE, 1HX, 1HP, 1HR /
      REWIND 8
      K = 0
      N = 0
      IER = 0
      NCARDS = 0
      FIRST = .TRUE.
 1000 CONTINUE
C
C***  THE FOLLOWING TWO CARDS ARE FOR FORTRAN-IV
C
C     READ(8,1060) (KOL(I), I=1,80)
C     IF(EOF(8)) 1040,1010
C
C***  THE FOLLOWING CARD IS FOR FORTRAN-V
C
      READ(8,1060,END=1040) (KOL(I), I=1,80)
C
C     SET THE NUMBER OF CARDS IN NLIST
C
 1010 CONTINUE
      IF(KOL(2) .NE. KAND) GO TO 1030
      IF(.NOT. TEST(KOL(3),KEXP,4)) GO TO 1030
          IF(FIRST .OR. (IER .GT. 0)) GO TO 1020
          IF(NLIST(K) .LT. 1000) NLIST(K) = NLIST(K)+1000*NCARDS
 1020     CONTINUE
          K = K+1
          NCARDS = 0
          FIRST = .FALSE.
          IF(K .GT. 100) IER = 1
 1030 CONTINUE
      NCARDS = NCARDS+1
      GO TO 1000
C
C     END OF FILE ENCOUNTERED ON TAPE-8
C
 1040 CONTINUE
      IF((NLIST(K) .LT. 1000) .AND. (IER .LE. 0))
     1  NLIST(K) = NLIST(K) + 1000*NCARDS
      KLIST = K
      IF(IER .EQ. 0) GO TO 1050
          WRITE(6,1070) KLIST
          KLIST = 100
 1050 CONTINUE
 1060 FORMAT(80A1)
 1070 FORMAT(23H0 **WARNING** THERE ARE,I4,18H EXPERIMENTAL DATA,
     1      44H NAMELISTS FOR THIS CASE, THE MAXIMUM IS 100 /
     2      14X,26HTHE FIRST 100 WILL BE USED //)
      RETURN
      END
