      SUBROUTINE ZERANG(ARG)
C
C     ----SUBROUTINE ZERANG USED TO INITIALIZE ANGLES FOR ANGLES ROUTINE
C
      DIMENSION ARG(6)
      DO 1000 I=1,6
         ARG(I)=0.
 1000 CONTINUE
      ARG(4)=1.
      RETURN
      END
